### ISSUE TITLE
null-aware on WidgetBinding is breaking on Flutter 2

### ISSUE THREAD

**Issue by nelsliu9121** [Milad-Akarie/auto_route_library#1070]
The latest release v4.0.1 is breaking for developers like me who are using Flutter 2.10.5 & Dart 2.16

Per the description from #1019 and also the PR from #1066, I dug out from flutter/flutter repo that they changed the following line to make it no longer nullable:

https://github.com/flutter/flutter/blob/6bba577bf230f5387ee01d7336ba755cb4c8bc9a/packages/flutter/lib/src/widgets/binding.dart#L273

I believe that Flutter 2.10.5 was the last stable release until we have 3.0.0, PR #1066 is a breaking change and should not be released without warning.

**Comment by Milad-Akarie** [comment]
@nelsliu9121 I agree, what happen was that I pushed major update (4.0.0) like two days before flutter upgraded to 3.0.0 and I thought it would be weird and it would confuse people to publish 2 major updates in 3 days. besides, I was thinking since it is a platform update everybody will just upgrade instantly.  

My bad thu

you can still restrict your build to 4.0.0 until you upgrade to flutter 3.0.0

**Comment by Su22101998** [comment]
How do I fix it though? I'm unable to use fl_charts due to this problem

**Comment by nelsliu9121** [comment]
@Su22101998 You should update your `pubspec.yaml` and mark the `auto_route` library(also its companion `auto_route_generator` package) to a fixed version of "4.0.0"

**Comment by nelsliu9121** [comment]
It looks like you're using a version of flutter SDK that's greater than 2.10.5.

### Flutter SDK <= 2.10.5

Use auto_route 4.0.0 & fl_chart 0.50.5

### Flutter SDK > 2.10.5

Use auto_route >= 4.0.1 & fl_chart >= 0.50.6

I believed that the fl_chart lib was updated to have Flutter 3.0 support a few days ago.
