### ISSUE TITLE
Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by amebrahimi** [Milad-Akarie/auto_route_library#1074]
I get this error when I want to run my application.
```
: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:20
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try accessing using ?. instead.
            location: WidgetsBinding.instance.window.defaultRouteName);
                                              ^^^^^^
: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:53
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try accessing using ?. instead.
      location: WidgetsBinding.instance.window.defaultRouteName);
                                        ^^^^^^
: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:64
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.addObserver(this);
                                               ^^^^^^^^^^^
: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:71
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.removeObserver(this);
                                               ^^^^^^^^^^^^^^
: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:80
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    if (hasListeners) WidgetsBinding.instance.removeObserver(this);
                                              ^^^^^^^^^^^^^^
: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/widgets/auto_route_navigator.dart:47
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
```

dependencies:
```
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
    auto_route: ^4.0.1

dev_dependencies:
    auto_route_generator: ^4.0.0
    build_runner: ^2.1.10
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
[√] Android Studio (version 2021.1)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.67.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by EALeeItsInTheC0de** [comment]
Dropping down to version 3.2.4 - is a temp fix for me

**Comment by amebrahimi** [comment]
@EALeeItsInTheC0de Yes.
Me too

**Comment by Milad-Akarie** [comment]
@amebrahimi @EALeeItsInTheC0de better downgrade to version 4.0.0 until you upgrade to flutter 3.0.0

**Comment by amebrahimi** [comment]
@Milad-Akarie you mean version 3.2.4 right?
because I tried 4.0.0 too it didn't work for me. same issue.

**Comment by Milad-Akarie** [comment]
@amebrahimi  I mean 4.0.0, the compatibility changes are made in 4.0.1
Make sure your version declaration doesn't include '^'.
so just 
auto_route: 4.0.0

**Comment by amebrahimi** [comment]
@Milad-Akarie  Oh, Sorry ok thank you

**Comment by arkeri** [comment]
> 

I am still facing with issue with 4.0.1

`: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:20
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try accessing using ?. instead.
                location: WidgetsBinding.instance.window.defaultRouteName);
                                                  ^^^^^^
: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:53
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try accessing using ?. instead.
          location: WidgetsBinding.instance.window.defaultRouteName);
                                            ^^^^^^
: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:64
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.
        if (!hasListeners) WidgetsBinding.instance.addObserver(this);
                                                   ^^^^^^^^^^^
: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:71
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.
        if (!hasListeners) WidgetsBinding.instance.removeObserver(this);
                                                   ^^^^^^^^^^^^^^
: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/provider/auto_route_information_provider.dart:80
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.
        if (hasListeners) WidgetsBinding.instance.removeObserver(this);
                                                  ^^^^^^^^^^^^^^
: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/widgets/auto_route_navigator.dart:47
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    Try calling using ?. instead.
          WidgetsBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^`
