### ISSUE TITLE
 Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by sn9854d** [Milad-Akarie/auto_route_library#1099]
*I'm getting the following error when I try to build the flutter app. *
***
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:20:47: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
            location: WidgetsBinding.instance.window.defaultRouteName);
                                              ^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:53:41: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
      location: WidgetsBinding.instance.window.defaultRouteName);
                                        ^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:64:48: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.addObserver(this);
                                               ^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:71:48: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.removeObserver(this);
                                               ^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:80:47: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (hasListeners) WidgetsBinding.instance.removeObserver(this);
                                              ^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/widgets/auto_route_navigator.dart:47:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {

**Comment by marcoAtEnvidual** [comment]
Same issue here :S

../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:20:47: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
            location: WidgetsBinding.instance.window.defaultRouteName);
                                              ^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:53:41: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
      location: WidgetsBinding.instance.window.defaultRouteName);
                                        ^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:64:48: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.addObserver(this);
                                               ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:71:48: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (!hasListeners) WidgetsBinding.instance.removeObserver(this);
                                               ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:80:47: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    if (hasListeners) WidgetsBinding.instance.removeObserver(this);
                                              ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/widgets/auto_route_navigator.dart:47:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/widgets/auto_tabs_router.dart:559:33: Error: The argument type 'Duration?' can't be assigned to the parameter type 'Duration' because 'Duration?' is nullable and 'Duration' isn't.
 - 'Duration' is from 'dart:core'.
          duration: typedWidget.duration,
                                ^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/widgets/auto_tabs_router.dart:577:31: Error: The argument type 'Duration?' can't be assigned to the parameter type 'Duration' because 'Duration?' is nullable and 'Duration' isn't.
 - 'Duration' is from 'dart:core'.
        duration: typedWidget.duration,
                              ^
../../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/widgets/custom_tab_bar_view.dart:153:44: Error: The getter 'animationDuration' isn't defined for the class 'TabController'.
 - 'TabController' is from 'package:flutter/src/material/tab_controller.dart' ('../../../fvm/versions/2.8.1/packages/flutter/lib/src/material/tab_controller.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'animationDuration'.
    final Duration duration = _controller!.animationDuration;
                                           ^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

**Comment by BrianMwas** [comment]
Same here
