### ISSUE TITLE
Handle Dynamic link or Deep link or App link

### ISSUE THREAD

**Issue by prasantco** [Milad-Akarie/auto_route_library#112]
In today's time, deep linking is being used on mobile end, and the option to handle it has been given in some other packages.
We need this feature inside this library. @Milad-Akarie can you suggest ur or provide this feature as soon as possible how to handle it along with parameters because we are ready to implement inside my production app.

**Comment by Milad-Akarie** [comment]
@visual-velocity  I'm actually currently working on web URL parameters so that should be a part of it. stay tuned!

**Comment by visual-velocity** [comment]
Thank you so much for giving this helpful information.

**Comment by Milad-Akarie** [comment]
Hey @visual-velocity by deep linking do you mean path parameters like '/users/:id or being able to navigate across nested navigators using a single path?

**Comment by visual-velocity** [comment]
Hi @Milad-Akarie 
Yes i mean path parameters like '/users/:id   and along with 
https://example.page.link/summer-sale
https://example.page.link/winter-sale?attr=hello
https://example.page.link/login

I am sharing this sample with you, I have to navigate the app on the basis of the path and attributes in the sample .
You create a Dynamic Link either by using the Firebase console, using a REST API, iOS or Android Builder API, or by forming a URL by adding Dynamic Link parameters to a domain specific to your app. These parameters specify the links you want to open, depending on the user's platform and whether your app is installed.

When a user opens one of your Dynamic Links, if your app isn't yet installed, the user is sent to the Play Store or App Store to install your app (unless you specify otherwise), and your app opens. You can then retrieve the link that was passed to your app and handle the deep link as appropriate for your app.

**Comment by visual-velocity** [comment]
I have to implement like this,Everything from single base route example
![image](https://user-images.githubusercontent.com/63794674/83070405-0f8bb800-a089-11ea-9bd1-acf509a80749.png)

**Comment by visual-velocity** [comment]
Wildcard parameter matching
Querystring parameter parsing

**Comment by Milad-Akarie** [comment]
@visual-velocity you would usually handle this part "https://example.page.link" by your own right?

**Comment by visual-velocity** [comment]
Hi,
Yes, we will handle it, it was just a sample URL, so a similar URL can also
be found, that's why I added a sample.

**Comment by Aerofluxx** [comment]
> Hey @visual-velocity by deep linking do you mean path parameters like '/users/:id or being able to navigate across nested navigators using a single path?

Absolutely on it! Thank you so much for this package Milad, I can't wait for this feature for Flutter Web. 

I'm trying to achieve this behavior since like 4 month now. My plan is to have my $baseUrl/orders - navigating the first main Router of my MaterialApp (onGenerateRoute function) and showing the user all orders. 

After the user enters the URL $baseUrl/orders/:id it should pass it through the main router (to provide the list of orders again) and hand it over to a nested router called "OrdersRouter". That one I want to bind on an ExtendedNavigator and show the orderDetails page.

I think u'll make a lot of people happy with your update! 
Thanks!
Mike

**Comment by visual-velocity** [comment]
Hey @Milad-Akarie ,any update regarding this issue, i need this feature urgently because we are waiting to add this feature in our production app

**Comment by Milad-Akarie** [comment]
Hey @visual-velocity I had to reconstruct the whole thing that's why it's taking this long.
I should be able to push a dev-version soon enough. but you should know that there's a lot of breaking changes in the upcoming version.

**Comment by visual-velocity** [comment]
Hi Milad,
This is very good news, it is good to know that you are going to publish a
Dev-version, the right thing is that your library is very clean and clean.
Therefore, we are waiting for the updated version of your library, and I am
ready to produce my company with your library. I have been waiting for your
updated version for many days. Please publish the Dev-version quickly.

**Comment by theweiweiway** [comment]
Closing issue due to:
- AutoRoute 1.x which has great support for deep linking
