### ISSUE TITLE
AutoRouter Guards in combination with Bloc

### ISSUE THREAD

**Issue by morzan1001** [Milad-Akarie/auto_route_library#1174]
Hi, first of all, I think my problem is not a problem of the AutoRouter package but my programming stupidity, but I need some help :) .

I am building a web application with Flutter. This means a user has access to the path and can therefore influence the autorouter. I want to prevent that a not logged in person can see parts of the website for which one must be logged in. 

I have seen AutoRouter offers `guards` to do exactly that. As a statemanament I use Bloc and here we come to the errors. I guess my BlocListener needs a context which AutoRouter does not provide. 

My Guard currently looks like this: 

```dart
class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    BlocListener<AuthenticationBloc, AuthenticationState>(
        listener: (context, state) {
      if (state is AuthenticationAuthenticated) {
        resolver.next(true);
      } else {
        router.navigate(const LoginRoute());
      }
    });
  }
}
```
Through theverse tests I have already found out that the if query is obviously not executed at all. 

I had also already tried the following: 
```dart
[...]
final context = router.navigatorKey.currentState!;
    if (BlocProvider.of<AuthenticationBloc>(context).state ==
        AuthenticationAuthenticated()) {
      resolver.next(true);
    } else {
[...]
```

But here is the problem, if a user is logged in and starts the application, e.g. a token is still stored and therefore a new login is not necessary, that then the application does not load anymore because obviously a `null` is returned when querying the context. 

Thank you very much for your help and ideas to this problem 😄

**Comment by morzan1001** [comment]
Oh, I have of course also tried to simply pass the context into the guard, but that does not work, because it seems as if you would then pass a context in which the BlocProvider does not yet exist. 🥲

**Comment by tcmhoang** [comment]
Do not access context inside the `AutoRouteGuard`.
Try passing your instance of `AuthenticationBloc` as an argument for `AuthGuard`. This will make your code more testable. Also, It works fine for me 😄 
Your code should look like this:
```dart
class AuthGuard extends AutoRouteGuard {
  AuthGuard(this._auth, this._fAuth);

  final AuthenticationBloc _auth;

  @override
  void onNavigation(
    NavigationResolver resolver,
    StackRouter router,
  ) 
    { 
    // your logic goes here 
    }

}
```

Notice: before initializing the `MaterialApp` you should provide the `AuthenticationBloc` for `AuthGuard` to instantiate. Without  `AuthGuard` instance, you cannot instantiate the `AppRouter` to pass to `MaterialApp`

**Comment by morzan1001** [comment]
Thanks for your suggestion, I had also thought about passing the AuthenticationBloc object but there is a problem. 

```
[...]
late final AppRouter appRouter;

  @override
  void initState() {
    appRouter = AppRouter(authGuard: AuthGuard());
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return buildBlocProvider();
  }

  Widget buildBlocProvider() {
    return MultiBlocProvider(
      providers: BlocProviders.providers,
      child: buildAdaptiveTheme(),
    );
  }

  Widget buildAdaptiveTheme() {
    return AdaptiveTheme(
[...}
      builder: buildMaterialApp(),
    );
  }

  // Widget Function(ThemeData light, ThemeData dark)
  buildMaterialApp() {
 [...]
          routerDelegate: appRouter.delegate(),
          routeInformationParser: appRouter.defaultRouteParser(),
        ),
      );
    };
  }
[...]
```

My router is created in the `initState` function of my `app.dart` (which is called in the `main.dart`) file. But the BlocProvider is only included in the `build` function as provider. That means in the `initState` I can't pass this context to the provider yet, but I don't know where else I can initialize the router. How did you solve this problem?

**Comment by tcmhoang** [comment]
In my opinion, refrain from using `Stateful Widget` while you're using bloc. It will make your application's states hardly predictable. 

In your situation, after providing the `AuthenticationBloc` in your `buildBlocProvider` method. You are safe to use [Builder](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget to get the instance of `AuthenticationBloc` in the `buildMaterialApp` method.

```dart
Builder(
  builder: (context) {
  final _auth = context.read<AuthenticationBloc>();
  final _router = AppRouter(authGuard: AuthGuard(_auth));
  // instantiate your material app here
  }
)
```

After doing so,  I believe your `AuthGuard` will be working as expected.

**Comment by morzan1001** [comment]
I have now done the whole thing exactly as you suggested. So I put the AppRouter in my `buildMaterialApp()` function and you are right, the AuthGuard works fine. thanks! 

But unfortunately this has caused other problems. When I start the app I check if there is an auth token in memory and if so the user is considered authenticated for now. Depending on this, a user must then be routed either to the login screen or to the main screen in the app. For this I have a wrapper class that is called first of all by the router. 

```dart
class _WrapperPageState extends State<WrapperPage> {
  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthenticationBloc, AuthenticationState>(
      listener: (context, state) {
        if (state is AuthenticationAuthenticated) {
          AutoRouter.of(context).navigate(const MasterRoute());
        } else {
          //if (state is AuthenticationUnauthenticated) {
          AutoRouter.of(context).navigate(const LoginRoute());
        }
      },
      child: const SafeArea(
        child: Scaffold(
          body: Center(
            child: LoadingIndicator(),
          ),
        ),
      ),
    );
  }
}
```

Until now the router was created before the blocs, so the router loaded the wrapper in the background and when the bloc was initialized and checked for a token, the correct route was triggered by the BlocListener. Because the bloc is now created before the router, the BlocListener is no longer notified. I have solved the whole thing somewhat inelegantly: 

```dart
final _auth = BlocProvider.of<AuthenticationBloc>(context);
final _appRouter = AppRouter(authGuard: AuthGuard(_auth));
Future.delayed(const Duration(milliseconds: 100), () {
  BlocProvider.of<AuthenticationBloc>(context).add(AppStart(isLoggedIn: isLoggedIn));
});
```

Do you have another idea how I can trigger the BlocListener? I had already thought about simply reading the status and making an If query, but that doesn't work. If the autorouter should route something and then a return is loaded with a widget, then the router routes but then loads the widget and you are back on the page from before. So I must somehow returnen something in the build function in the wrapper and still route.

**Comment by tcmhoang** [comment]
If I understand your question correctly, the `BlocListener` does not work for you when the `AuthenticationBloc` instantiated before you routed to the `WrapperPage`

In `BlocListener` document
> Takes a [BlocWidgetListener](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocWidgetListener.html) and an optional [bloc](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListenerBase/bloc.html) and invokes the [listener](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListenerBase/listener.html) in response to state changes in the [bloc](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListenerBase/bloc.html).

It pointed out that when the `BlocListener` is used, it will only listen to the states of the bloc if and only if the states changes when the `BlocListener` widget is fully rendered.

As you noticed, the first case was worked because by the time your `AppRouter` routed to the `WrapperPage`. The `AuthenticationBloc` had been recently instantiated. I guess that the state of the bloc changed when it had been freshly created by the time the `BlocListener` was rendered. And so it invoked the statement in the `listener` property.

But in the second case, you provided the `AuthenticationBloc` in the `AppRoute`. The state changes you saw in the first case no longer happened in the `WrapperPage`. Because it occurred when it had been instantiated by the `AuthGuard`. By the time you routed to the `WrapperPage`, the state such as `authenticated` or `unauthenticated` was already determined. So no event would be listened to by `BlocListener`.

I suggest that instead of using `BlocListener` in the `WrapperPage`. You should only read the state of the `AuthenticationBloc` in the `build` method of the `WrapperPage`. 

Your code should somewhat like:

```dart
class _WrapperPageState extends State<WrapperPage> {
  @override
  Widget build(BuildContext context) {
   final state = context.read<AuthenticationBloc>().state;
   if (state is AuthenticationAuthenticated) {
          AutoRouter.of(context).navigate(const MasterRoute());
        } else {
          //if (state is AuthenticationUnauthenticated) {
          AutoRouter.of(context).navigate(const LoginRoute());
        }
    return  const SafeArea(
        child: Scaffold(
          body: Center(
            child: LoadingIndicator(),
          ),
        ),
      );
  }
}
```

**Comment by hassank185** [comment]
Hello tcmhoang,

**Comment by tcmhoang** [comment]
I don't have any context about the problem you're having. Therefore, I make my best guess here that you want to know how to make them come together. I put a simple demo here and hopefully, you will get the idea

First, you need to have your own `Bloc` handling authentication with the states, events, and logic that you desire for your application. 
In my case, I will call it `AuthenticationBloc`

```dart 
class AuthenticateBloc
    extends Bloc<AuthenticateEvent, AuthenticateState> {
  AuthenticateBloc()
      : super(const AuthenticateState.initial()) {
    // Need to implement the logic
  }
}
```

In `AuthGuard`, a class extends `AutoRouteGuard`. It depends on the argument of type `AuthenticationBloc` to use the bloc's logic in the route guard.

```dart
class AuthGuard extends AutoRouteGuard {
  AuthGuard(this._auth);

  final AuthenticationBloc _auth;
  @override
// Need to implement this
  Future<void> onNavigation(
    NavigationResolver resolver,
    StackRouter router,
  ) async =>
              _auth.state.maybeMap(
                orElse: () => resolver.redirect(),
                authenticated: (_) =>  resolver.next();,
              )
         ;
}
```

Finally, to make them work. Provide the `AuthenticationBloc` in the outermost layer when you call the `runApp` method. Then, we can retrieve it via context and pass it to the `AppRouter` constructor to make the router aware of your custom guard.


```dart
void main() {
  runApp(
    BlocProvider(
      create: (_) => AuthenticationBloc(),
      child: Builder(
        builder: (ctx) {
          final _appRouter =
              AppRouter(authGuard: AuthGuard(ctx.read(), ctx.read()));

          return MaterialApp.router(
            routeInformationParser: _appRouter.defaultRouteParser(),
            routerDelegate: _appRouter.delegate(),
          );
        },
      ),
    ),
  );
}
```

**Comment by hassank185** [comment]
Thanks for the response. 
Iam using the subset of bloc which is Cubit and here's the authentication cubit:

`class AuthCubit extends Cubit<AuthState> {
  final IsSignInUseCase isSignInUseCase;
  final GetCurrentUidUseCase getCurrentUidUseCase;
  final SignOutUseCase signOutUseCase;

  AuthCubit({
    required this.isSignInUseCase,
    required this.signOutUseCase,
    required this.getCurrentUidUseCase,
  }) : super(AuthInitial());

  Future<void> appStarted() async{
    try{
      bool isSignIn=await isSignInUseCase.call();

      if (isSignIn){
        final uid=await getCurrentUidUseCase.call();
        emit(Authenticated(uid: uid));
      }else
        emit(UnAuthenticated());

    }catch(_){
      emit(UnAuthenticated());
    }
  }
  Future<void> loggedIn() async{
    try{
      final uid= await getCurrentUidUseCase.call();
      emit(Authenticated(uid: uid));
    }catch(_){

    }
  }
  Future<void> loggedOut() async{
    try{
      await signOutUseCase.call();
      emit(UnAuthenticated());
    }catch(_){}

  }
}`

Also can you check the AuthGuard if iam doing something wrong make me correct Here it is:

`import 'dart:async';

import 'package:auto_route/auto_route.dart';
import 'package:plant_port_app/features/app/main_screen/main_screen.dart';
import 'package:plant_port_app/routes/auto_route/auto_route_imports.gr.dart';
import 'package:plant_port_app/user/presentation/cubit/auth/auth_cubit.dart';
import 'package:plant_port_app/injection_container.dart' as di;
class AuthGuard extends AutoRouteGuard {
  final AuthCubit authCubit;
  StreamSubscription<AuthState>? _authSubscription;

  AuthGuard(this.authCubit);

  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    authCubit.stream.listen((state) {
      print("guard started");
      if (state is Authenticated) {
        resolver.next(true);
      } else {
        resolver.next(false);
        router.push(SignUpPage());
      }
    });


  }

}

`

And lastly in the main.dart my code structure is like that iam using the multiBlocProvider and have multiple blocs so i will i handle this :

`import 'package:auto_route/auto_route.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:plant_port_app/features/app/main_screen/main_screen.dart';
import 'package:plant_port_app/global/styles.dart';
import 'package:plant_port_app/routes/auth_guard/auth_guard.dart';
import 'package:plant_port_app/routes/auto_route/auto_route_imports.dart';
import 'package:plant_port_app/routes/auto_route/auto_route_imports.gr.dart';
import 'package:plant_port_app/routes/getit/get_it_config.dart';
import 'package:plant_port_app/user/presentation/cubit/auth/auth_cubit.dart';
import 'package:plant_port_app/user/presentation/cubit/credential/credential_cubit.dart';
import 'firebase_options.dart';
import 'injection_container.dart' as di;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await di.init();
  runApp(const MyApp(
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(360, 690),
        minTextAdapt: true,
        splitScreenMode: true,
        builder: (context, child) {
          return MultiBlocProvider(
            providers: [
              BlocProvider(
                create: (context) => di.sl<AuthCubit>()..appStarted(),
              ),
              BlocProvider(create: (context) => di.sl<CredentialCubit>()),
            ],
            child: MaterialApp.router(
              debugShowCheckedModeBanner: false,
              routerDelegate: _appRouter.delegate(),
              routeInformationParser: _appRouter.defaultRouteParser(),
              theme: ThemeData(
                colorScheme: const ColorScheme.light(
                  primary: primaryColor129C52,
                ),
                appBarTheme: const AppBarTheme(
                  color: secondaryColorWhiteFFFFFF,
                  surfaceTintColor: Colors.transparent,
                ),
                useMaterial3: true,
              ),
              title: 'Plant Port',
            ),
          );
        });
  }
}
`
These line of codes is having error because i didnt define the _appRouter just wanted to see how you can access the AuthGuard:

```
    routerDelegate: _appRouter.delegate(),
              routeInformationParser: _appRouter.defaultRouteParser(),
              
              
```

Thanks

**Comment by hassank185** [comment]
The code i write in the AuthGuard is not emitting and i tried to access it in the main.dart like you mentioned above in the demo @tcmhoang 

```void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await di.init();
  runApp(
    BlocProvider(
      create: (context) => di.sl<CredentialCubit>(),
      child: BlocProvider(create: (_) => di.sl<AuthCubit>(),
        child: Builder(
          builder: (ctx) {
            final _appRouter = AppRouter(authGuard: AuthGuard(ctx.read()));
            return ScreenUtilInit(
              designSize: const Size(360, 690),
              minTextAdapt: true,
              splitScreenMode: true,
              child: MaterialApp.router(
                debugShowCheckedModeBanner: false,
                routerDelegate: _appRouter.delegate(),
                routeInformationParser: _appRouter.defaultRouteParser(),
                theme: ThemeData(
                  colorScheme: const ColorScheme.light(
                    primary: primaryColor129C52,
                  ),
                  appBarTheme: const AppBarTheme(
                    color: secondaryColorWhiteFFFFFF,
                    surfaceTintColor: Colors.transparent,
                  ),
                  useMaterial3: true,
                ),
                title: 'Plant Port',
              ),
            );
          },
        ),),
    ),
  );
}```


Still didnt find any Solution

**Comment by tcmhoang** [comment]
The main job of `AuthGuard` is to read the current authentication state. And I believe you can read the current state of `Cubit` via the `state` property, you do not need to use `StreamSubscription`. And it is the culprit that causes this bug.

FYI, Your cubit does change the state when you call `appStarted` method on it. But the state is already settled when you initialize the `AuthGuard`.  When you listen to `Cubit` state stream every time you navigate around the app. It does nothing because the state does not change.

**Comment by hassank185** [comment]
Everything works fine and the user authenticate and created in the firebase but still it does not navigate to the home even i tried to navigate him.

**Comment by hassank185** [comment]
I used print statement to check the flow in the auth guard its not emitting when the flow called

**Comment by hassank185** [comment]
The behavior i want is to navigate user to the homePage and keep him logged in until he manually logged out himself.

**Comment by tcmhoang** [comment]
Without context and implementation, I can't help you much. You might find my approach to this problem in this [project](https://github.com/Revup-vn/revup-flutter-app-admin/blob/main/lib/login/view/login_page.dart) helpful.

**Comment by comancheo** [comment]
Hello there,
I have struggled with same problem. Apperantly, you can init BLOC and assign it to some global variable.
`BlocProvider<PersonBloc>(
  lazy: false,
  create: (context) {
    return globals.personBloc = PersonBloc();
},)`
And use this variable inside AuthGuard, you have to wait until the variable isn't null (just use `if(globals.personBloc!=null){///your logic here}` else { Future.delayed(Duratin(miliseconds:100),(){onNavigation();}); }`

Works fine.
