### ISSUE TITLE
How to pre-set initial index value for TabRouter?

### ISSUE THREAD

**Issue by SergeyNemesh** [Milad-Akarie/auto_route_library#1217]
Thank for great  tool. I cant find out how to set initial value for AutoTabsScaffold(bottomNavigationBuilder: (context,  TabsRouter )).
For example i need that initial tab should be (second), but "int _activeIndex = 0;" Does some way to change in for initial _activeIndex?

**Comment by Milad-Akarie** [comment]
@SergeyNemesh because auto_route treats `AutoTabsRouter` which `AutoTabsScaffold` is a wrapper of, as a router that you can deep-link into, you can't set the initial tab index by passing an initialActiveIndex, you do it by setting the initial childRoute of the parent route. 
e.g you can set it from the router delegate
`_rootRouter.delegate(initialRoutes: [MyTabsRouter(children:[MyInitialTabRoute()])]);`;
this way you can check if you your App is launched from a deep-link and it that case don't manually set the initialRoutes. 

same thing if you're navigating to the TabsHostRouter
`context.pushRoute(MyTabsRouter(children:[MyInitialTabRoute()]));`
`context.navigateTo(MyTabsRouter(children:[MyInitialTabRoute()]));`
