### ISSUE TITLE
Web URL Path bug

### ISSUE THREAD

**Issue by adpmhel24** [Milad-Akarie/auto_route_library#1279]
I've manually type may path in the browser. http://localhost:53493/sales/price_quotation/3
When I hit enter it says that PriceQuotationHeaderDetailsRouteArgs can not be null because it has a required parameter, 
This is my auto route details 
```
CustomRoute(
            transitionsBuilder: TransitionsBuilders.noTransition,
            durationInMilliseconds: 5,
            page: PriceQuotationHeaderDetailsPage,
            path: ":id",
            ),
```

**Comment by Milad-Akarie** [comment]
@adpmhel24 it seems your page PriceQuotationHeaderDetailsPage has required arguments

**Comment by mugikhan** [comment]
@adpmhel24 You can use normal routing with the RouteArgs (`navigate() instead of navigateNamed()`). Navigating via paths is broken and has been for a while. 

@Milad-Akarie All path params have to be required as per your statement [here](https://github.com/Milad-Akarie/auto_route_library/issues/1214#issuecomment-1240550472) that optional paths are not supported. So that makes path params either required or might have to declare them as late which would be bad practice.

**Comment by adpmhel24** [comment]
sorry guys i forgot that there's 2 parameter in my PriceQuotationHeaderDetailsPage. :)

**Comment by mrverdant13** [comment]
@mugikhan @Milad-Akarie 
I am facing this issue when using path-based navigation. The typed-route-based navigation works as expected, tho.
I've been running my app on mobile and desktop without trouble. Then, when trying on web, it wouldn't even warn about this flaw.
If path-based navigation has been broken for a while, I believe it should be pointed out in a `Known issues` section of the main Readme file, so devs can be aware of it.
