### ISSUE TITLE
[Question] When does `didReplace` gets invoked in an `AutoRouterObserver`?

### ISSUE THREAD

**Issue by mrverdant13** [Milad-Akarie/auto_route_library#1285]
I am currently implementing a custom `AutoRouterObserver` for analytics integration purposes.

I have not managed to identify the conditions under the `didReplace` method is called.
I have tried with `navigateNamed`, `replaceNamed` and `replaceAll` for a given route with no luck.

As a side note, I am also using a delegate listener to watch the URL changes, and it is working as expected even for the same path with different query parameters, case in with not even a single `AutoRouteObserver` method is triggered.

**Comment by tyler401go** [comment]
This is a very old question, but I am seeing similar behavior that I cannot figure out. I am using callbacks such as `didPop`, `didPush`, `didRemove`, and trying to use `didReplace`. However, instead of `didReplace` getting called when using `replace`, instead a `didPush` then `didRemove` is being fired instead. This seems incorrect for the `AutoRouterObserver`. Any insight?
