### ISSUE TITLE
How do I get the current route name?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/auto_route_library#131]
I am using the auto_route version ^0.5.0 and how do I get the current route?

I used `ModalRoute.of(context).settings.name;` but it outputs `/` always.

```dart
 ExtendedNavigator.of(context).pushNamed(
      Routes.someScreen,
      arguments: SomeScreenArguments(),
    );
```

**Comment by ganeshrvel** [comment]
@Milad-Akarie Any updates on this?

**Comment by ganeshrvel** [comment]
I found a similar issue https://github.com/flutter/flutter/issues/14243#issuecomment-602063460

**Comment by Milad-Akarie** [comment]
Hey @ganeshrvel  you actually need to be inside of a route's widget to get it's name using ModalRoute.of(context).settings.name

**Comment by ganeshrvel** [comment]
@Milad-Akarie how else do i get the current route name? It is very important for me to get there value

**Comment by Milad-Akarie** [comment]
@ganeshrvel I'm still working on this. I tried using a NavigatorObserver but the problem I faced is that flutter notifies deep initial routes push-status in reverse order. for example if I set initial route to /second-page navigator will push "/" then "/second-page" because it works in a deeplinks style but the problem is my observer will get "/second-page" first then "/", I still don't get the logic behind this, but any ways if you don't have any weird initial routes cases I guess you could use this NavigatorObserver

```
class StackObserver extends NavigatorObserver {
  final stack = <Route>[];
  List<String> get history => stack.map((r) => r.settings.name).toList();

  String get current => stack.last.settings.name;

  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    stack.add(route);
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic> previousRoute) {
    stack.remove(route);
  }

  @override
  void didRemove(Route<dynamic> route, Route<dynamic> previousRoute) {
    stack.remove(route);
  }

  @override
  void didReplace({Route<dynamic> newRoute, Route<dynamic> oldRoute}) {
    final index = stack.indexOf(oldRoute);
    stack[index] = newRoute;
  }
}
```
you could have the instance as injectable or define it as a global variable inside of your main file then pass it to 
```dart
ExtendedNavigator(..., observers : [stackObserverInstance]):
```

**Comment by ganeshrvel** [comment]
great thank you!
