### ISSUE TITLE
Unit testing named/path navigation

### ISSUE THREAD

**Issue by jjoelson** [Milad-Akarie/auto_route_library#1385]
Hi all! Thanks for this great package; I've been loving how much it simplifies my routing code.

One thing I've been trying to figure out is how I can write tests to ensure that path navigation using `navigateNamed` results in the route hierarchy that I expect. Something that I've experimented with is defining a few helpers to extract the router's current navigation hierarchy in a form against which I can easily write tests:
```dart
class RouteHierarchy extends Equatable {
  final String name;
  final List<RouteHierarchy> children;

  const RouteHierarchy(this.name, [this.children = const []]);

  @override
  List<Object?> get props => [name, children];
}

extension GetRouterRouteHierarchy on RootStackRouter {
  List<RouteHierarchy> getRouteHierarchy() {
    return [
      for (final data in stackData) data.route.getRouteHierarchy(),
    ];
  }
}

extension GetRouteHierarchy on RouteMatch {
  RouteHierarchy getRouteHierarchy() {
    final childHierarchies = children
            ?.map((childMatch) => childMatch.getRouteHierarchy())
            .toList() ??
        [];
    return RouteHierarchy(name, childHierarchies);
  }
}
```

That allows me to write tests like this:
```dart
test('navigates to home', () async {
  final router = AppRouter();

  await router.navigateNamed(
    '/applinks/home',
    includePrefixMatches: true,
  );

  expect(
    router.getRouteHierarchy(),
    equals(
      const [
        RouteHierarchy('TabsRoute', [
          RouteHierarchy('HomeTabRoute', [
            RouteHierarchy('HomeRoute'),
          ]),
        ]),
      ],
    ),
  );
});
```

This seems to work pretty well, but I'm curious if something already exists in `auto_route` to help with this kind of test. I'm a bit concerned that my code here won't work for all types of hierarchies, or that it relies on implementation details of the package that may change in the future. Not to mention that it doesn't do anything to verify parameters.

I do think it would be great to have some mechanism built in to the package to allow us to write tests like this so that we don't need to use heavy integration tests in order to ensure that deep links work as expected. I'm happy to take a look at adding something like this, but since there's a lot of complexity within the package that I don't understand very well, I thought I'd submit this issue to see if this seems like something that could even be feasible.

**Comment by Milad-Akarie** [comment]
Hey @jjoelson  this would work for a single navigation but as you do multiple navigations you will not get the actual current hierarchy as `RouteMatch` only holds the initial segments from when it was created, it does not track the sub-stack changes. 

as I saw the need of this through your explanation I created a new method called  `currentHierarchy`, this method should always return the actual stack hierarchy including `pendingRoutes` (routes that has not been turned into pages yet) which is also important if you're doing a unit-test not an  integration-test. 

I also thought it's important to add an option to ignore pop-completers for unit-testing, this does not effect path-navigation because  it does not return pop completers

this's a sample of a simple hierarchy test using the newly added helpers

```dart
void main() {
  late NestedRouter router;
  setUp(() {
    router = NestedRouter()..ignorePopCompleters = true;
  });

  test('test route hierarchy', () async {
    await router.pushNamed('/second');
    expect(router.currentHierarchy(), [
      const HierarchySegment(
        SecondHostRoute.name,
        children: [
          HierarchySegment(SecondNested1Route.name),
        ],
      ),
    ]);
  });
}
```
you can chose weather to ignore path/query parameters in get `router.currentHierarchy(ignoreParams: true);`

I also added this handy extension for debugging
` print(router.currentHierarchy().prettyMap);`

```json
{
  "SecondHostRoute": {
    "children": {
      "SecondNested1Route": {}
    }
  }
}
```

**Comment by jjoelson** [comment]
This looks great, exactly what I'm looking for!
