### ISSUE TITLE
Web.How to check if page opened from browser directly

### ISSUE THREAD

**Issue by zombie6888** [Milad-Akarie/auto_route_library#1393]
Hello our app is mostly web-oriented. I'am using includePrefixMatches option setted to true. And i am using navigateBack() for back button. My goal is if user type in browser page home/page1/page2 directly he was able to go back to home/page1, then go back to home page. It works if i use pop() method. My first idea is check if user come directly from browser use pop() method, otherwise if he come from any other page use navigateBack(). But page stack is the same for both cases. Is it posiible to check somehow if page was opened directly from browser?

**Comment by Milad-Akarie** [comment]
Hey @zombie6888 I remember facing this use-case before, I think what I came up with was implementing what I called 'navigateUpOrBack'  and this's how it works: 

the url state has a list of liner segments ['home',' page1',  'page2',]
so I simply. check if url segments have more than 1 item then I can navigate up  to ->  ['home',' page1'] but if the url state has only one segment then I call navigate back

this ofcourse will add a new entry to the browser history stack but I guess that can be fixed with a forced url replace.

let me know such implementation would work for you.

p.s I don't recommend using pop() in web Apps at all.

**Comment by zombie6888** [comment]
Thank you for the reply. I've checked context.router.urlState.segments and it's always same length on the pages regardless of where you came from, other page of app or directly from browser. canNavigateBack method is also return true for both cases. It would be great, if you could share of your implementation

**Comment by Milad-Akarie** [comment]
@zombie6888  try this

```dart
extension AppRouterX on AppRouter {
 void navigateUpOrBack() {
    if(urlState.segments.length > 1){
      // keep this if you want the new
      // url to replace the current
       markUrlStateForReplace();
       navigateAll(urlState.segments..removeLast());
    }else {
      navigateBack();
    }
  }
}
```
