### ISSUE TITLE
Pop until method is not working (it's just going back)

### ISSUE THREAD

**Issue by KaushickSArgekar** [Milad-Akarie/auto_route_library#141]
ExtendedNavigator.ofRouter<Router>()
        .popUntil(ModalRoute.withName(className));

When we use this it's not going back to a particular class. it's just going back to the previous screen.
but in the old version, it was working fine.

**Comment by Milad-Akarie** [comment]
Hey @KaushickSArgekar Thanks for drawing my attention to this. It's happening because route names can't be used as anchors now that we was dynamic paths.
E.g path can be `/users/:id` and the pushed name is `/usere/1`

I already implemented this in version 0.6.1
You could use
` popUntil(RouteData.withPath(..))`
Or the simplified method I added
`popUntilPath(..)` or `popUntilRoot()`
Thanks again for reporting.

**Comment by KaushickSArgekar** [comment]
Hey @Milad-Akarie,
Just checked the popUntilPath it's working.
Thanks for the response.
