### ISSUE TITLE
request: Why is `final List<AutoRoute> routes = []` needed now that all routes already have @RoutePage?

### ISSUE THREAD

**Issue by simplenotezy** [Milad-Akarie/auto_route_library#1424]
I was at first very excited to see the addition of `@RoutePage`, as I thought it would remove the need for the generated router, e.g. doing this:

```dart
 @override      
 final List<AutoRoute> routes = [      
   //HomeScreen is generated as HomeRoute because     
   //of the replaceInRouteName property    
   AutoRoute(HomeRoute.page),    
  ]
```

Right now it feels like duplicate work, both having to add it to the list of AutoRoute as well ass add `@RoutePage` to your class.

Whereas this seems much more straightforward (and thus ignoring the `routes` array completly:

```dart
@RoutePage(
      transitionsBuilder: TransitionsBuilders.noTransition,
      durationInMilliseconds: 0,
      reverseDurationInMilliseconds: 0,
      fullscreenDialog: true,
      path: '/',
)
class MyCoolScreen extends StatelessWidget {}

**Comment by Milad-Akarie** [comment]
It's because of nested routing, we need a way to create the navigation hierarchy.

You have no idea how much I love the idea of just annotating the page, in-fact that was auto_route 0.1.0

Id love to hear any ideas regarding this

**Comment by simplenotezy** [comment]
Aha! I see, thanks for the response Milad.

I didn't know hierarchy was of importance; I've been developing an mobile app for the past year, and don't think I've come across needing to think about that (usually just use .pop(), .push() and .replace() and control hierarchy by logic in code).

An idea could perhaps be to add an optional `index` parameter to `RoutePage` that could control hierarchy. 

An alternate way, could be to add an `final List<AutoRoute> hierarchy` to AppRouter, that works this way:
1. It's index based so any routes provided there will get that index
2. If the route is not provided, it looks at `RoutePage@index` property
3. If index is not provided, it defaults to null, in bottom of hierarchy

**Comment by slavap** [comment]
@Milad-Akarie @simplenotezy 
Despite of fact I don't like this routes, it is still needs to be accessible (even if autogenerated somehow), because it is needed for adjusting initial route in runtime based on application settings, so I'm using the following class:
```dart
import 'package:auto_route/auto_route.dart';
import 'package:collection/collection.dart';
import 'package:flutter/widgets.dart';
import 'package:sw/common/empty.dart';

import 'navig_flow.dart';
import 'router.dart';

// See https://github.com/Milad-Akarie/auto_route_library/issues/644
class AppRouterEx extends AppRouter {
  List<AutoRoute> _routes = [];

  AppRouterEx([GlobalKey<NavigatorState>? navigatorKey]) : super(navigatorKey);

  List<AutoRoute> get superRoutes => super.routes;

  AutoRoute? findRoute(PageRouteInfo route) {
    final r = routes.firstWhereOrNull((e) => e.name == route.routeName);
    return r;
  }

  @override
  List<AutoRoute> get routes {
    if (_routes.isEmpty) {
      var lst = super.routes;
      PageRouteInfo landing = NavigFlow.landing;
      final landingRoute = lst.firstWhereOrNull((e) => e.name == landing.routeName);
      //FIXME: remove when fixed https://github.com/Milad-Akarie/auto_route_library/issues/1427
      String landingPath = '';
      try {
        landingPath = landingRoute?.path ?? '';
      } catch (ex) {
        // safe to ignore
      }
      if (landingRoute != null && landingPath != '/') {
        lst.removeWhere((e) => e.name == landing.routeName);
        final landingRouteNew = landingRoute.changePath('/');
        lst.add(landingRouteNew);
        if (isNotEmpty(landingPath)) lst.add(RedirectRoute(path: landingPath, redirectTo: '/'));
      }
      _routes = lst;
    }
    return _routes;
  }
}
```
Actually it could be useful not only for adjusting initial route, but perhaps other paths in runtime based on app settings.
So if something is going to be changed about routes, we still need a way to adjust paths in runtime.

**Comment by Milad-Akarie** [comment]
@slavap I totally agree, the new goal was the have more control over routes in runtime. 
@simplenotezy I'm worried more about nested-hierarchy, I'm thinking we could create a veriant @RoutePage annotation or a named constructor e.g @RoutePage.listed(path: '/', ...) and then generate a lazy list of those routes  when you can do something like this 

```dart
 @override      
 final List<AutoRoute> routes = this.defaultList; // defaultList is auto_generated
```

or you can mix and match as need
```dart
 @override      
 final List<AutoRoute> routes = [
    ...this.defaultList,
    AutoRoute(....),
    AutoRoute(....),
    ]
```
this way everyone wins, if you're working on a mobile App with a single router you can use the defaultList approach otherwise use the current one.

any ideas?

**Comment by simplenotezy** [comment]
Sounds good. Perhaps prepend the defaultList automatically under-the-hood, instead of having the developer to do it? Or is there a case where you would maybe append, or not have them at all?

**Comment by Milad-Akarie** [comment]
@simplenotezy that's debatable, the issue here is how to pass an AutoRouteGuard for example or any non-static props. this still needs some processing.

**Comment by Milad-Akarie** [comment]
Hey @FERNman for some reason I didn't get a prompt for your comment before, but this's a really interesting idea, as for the guard as widget matter I don't think it's that simply, because guards are supposed to prevent you from loading the target, on web that would mean changing the url before resolving the guard. 

but I guess we can mix and match, I'll try to find a way to override  auto generated routes.
