### ISSUE TITLE
How to give path names for nested-initial routes?

### ISSUE THREAD

**Issue by dhruv-js** [Milad-Akarie/auto_route_library#1490]
As mentioned in docs, after migrating to v6, one has to give empty path (path:"") as "initial" flag is removed. 
Currently, I am giving path names to nested-initial routes too.
Example:
`AutoRoute(
    page: GarageRoute, 
    path:'garage',  
    children : [
        AutoRoute(
            page: EmptyCarRoute, 
            path: 'car', 
            children: [
                AutoRoute(
                    page: AddCar,
                    path: 'add',
                    initial:true,
                    )
                ]
            ]
    )`

It would be really helpful if I can migrate the same to v6 keeping the 'AddCar' route 'initial' as well as keeping the path same as in the above example.

**Comment by Milad-Akarie** [comment]
@dhruv-js all inital did before is generate a redirect-route
you can still add it manually
`RedirectRoute(path: '', redirectTo: 'Addcart')`

**Comment by Milad-Akarie** [comment]
@dhruv-js turns out removing the initial flag is a bad idea, I brought it back in version 6.3.0

**Comment by Milad-Akarie** [comment]
@mrverdant13 I didn't think it was used by this many people, so I didn't give it a lot of thought at first,  I took it off because it required hierarchy awareness which wasn't obvious how to obtain when I first resigned v6 but now that I figured out a way to do it i thought it's better to bring it back.
