### ISSUE TITLE
AutoRouterState is unavailable in 6.2.0

### ISSUE THREAD

**Issue by dannyalder88** [Milad-Akarie/auto_route_library#1496]
I'm using a global key to access a router controller as described in the documentation. Upgrading to 6.2.0 seems to make **AutoRouterState** private and so it cannot be used as a type and breaks functionality. Should we be moving to a different way of accessing the controller?

Example from documentation:
```
class DashboardPage extends StatefulWidget {                
  @override                
  _DashboardPageState createState() => _DashboardPageState();                
}                
                
class _DashboardPageState extends State<DashboardPage> {                
  final _innerRouterKey = GlobalKey<AutoRouterState>();                
  @override                
  Widget build(BuildContext context) {                
    return Row(                
      children: [                
        Column(                
          children: [                
            NavLink(label: 'Users',                
            onTap:(){                
               final router = _innerRouterKey.currentState?.controller;                
               router?.push(const UsersRoute());                
             }                
            ),                
            ...                
          ],                
        ),                
        Expanded(                
          child: AutoRouter(key: _innerRouterKey),                
        )                
      ],                
    );                
  }                
}
```

**Comment by Milad-Akarie** [comment]
Damn it forgot why I kept it public in previous versions. Ya Ill make it public again

Although I would implement the above case using the builder since im not a bog fan of global keys

Make AutoRouter the root widget and use the builder property 
AutoRouter(builder:(ctx, child){})

The child passed to the builder is the rendered router so think of the builder as wrapper

This way you have access to a context with scoped router in it

**Comment by Milad-Akarie** [comment]
@dannyalder88 its public again
