### ISSUE TITLE
navigatorKey in v6

### ISSUE THREAD

**Issue by ondanplatform** [Milad-Akarie/auto_route_library#1564]
in v5 we could : 

```
AppRouter(
    navigatorKey: navigatorKey,
    authGuard: AuthGuard(),
  );
```

how can I do in v6 ?

**Comment by Milad-Akarie** [comment]
@ondanplatform Try this
```dart
@AutoRouterConfig()      
class AppRouter extends $AppRouter {  
    // add constructor
   AppRouter({super. navigatorKey}):
}
```

**Comment by ondanplatform** [comment]
thanks

**Comment by ziyadsfaxi** [comment]
Maybe someone can learn from my stupid mistake 😅:

After upgrading from `v4` to `v7`, I wanted to set `navigatorKey` to `Get.key` and I did that by overriding the `navigatorKey` in the `AppRouter` class:

```dart
WRONG CODE DONT COPY
 
@AutoRouterConfig()      
class AppRouter extends $AppRouter {  
   
  @override
  GlobalKey<NavigatorState> get navigatorKey => Get.key;       WRONG CODE DONT COPY 
}
```
After doing that, the navigation worked as expected except that in nested routes the `AutoLeadingButton` & `BackButton` were not working. I spent a lot of time before I figured the issue was with the `navigatorKey`.
