### ISSUE TITLE
Using streams as parameter for route

### ISSUE THREAD

**Issue by komarekw** [Milad-Akarie/auto_route_library#16]
Hi, 
we have an issue if we are using stream as a parameter of a route. We got this error:

`Compiler message:
lib/routes/router.gr.dart:12:8: Error: Not found: 'dart:async/stream.dart'
import 'dart:async/stream.dart';`

Is there a possibility to use streams as parameters?

Thanks,
Werner

**Comment by kuhnroyal** [comment]
This sounds like something one should not do.

**Comment by wwwdata** [comment]
> This sounds like something one should not do.

could you explain why?

**Comment by Milad-Akarie** [comment]
Hey @komarekw, it seems like the problem is in the generated import statement, I'll fix that in the next build. 
 Technically you can pass any kind of objects to your routes, but I don't think you should pass listenable/subscribable objects like streams or value notifiers consider providing your listenable up your widgets tree instead then access them throughout the context anywhere in your widgets tree.
and if you're just interested in returning a result from your destination considering awaiting for the navigator.   
Thanks for reporting.

**Comment by wwwdata** [comment]
@Milad-Akarie thanks! yes, we also now worked around the problem by passing a normal value and providing all the streams via context.

**Comment by kuhnroyal** [comment]
@wwwdata You will run into all kinds of pitfalls with this, unclosed sinks, potential memory leaks, streams that have already been listened to etc.
Try to always pass simple parameters (ids, names, urls etc.) and use Providers or whatever state pattern you prefer to look up your dependencies in the next route.

**Comment by Milad-Akarie** [comment]
Importing core classes like Stream is now skipped in v0.2.2
Thanks for reporting
