### ISSUE TITLE
Uri Error

### ISSUE THREAD

**Issue by Santa160** [Milad-Akarie/auto_route_library#1726]
: Error: No named parameter with the name 'uri'.
route_information_parser.dart:55
  }) : super(uri: uri, state: state);
             ^^^
: Error: No named parameter with the name 'uri'.
auto_router_delegate.dart:87
          RouteInformation(uri: Uri.parse(url)),

**Comment by AlexDochioiu** [comment]
Getting the same build error too

**Comment by AlexDochioiu** [comment]
```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/auto_route-7.8.1/lib/src/router/provider/auto_route_information_provider.dart:34:11: Error: No named parameter with the name 'uri'.
```

**Comment by AlexDochioiu** [comment]
Worth mentioning that I am on version: "7.8.1" because I am postponing the upgrade to flutter 3.13 (blurs and shadows are very broken in this flutter version)

**Comment by heshaShawky** [comment]
> Worth mentioning that I am on version: "7.8.1" because I am postponing the upgrade to flutter 3.13 (blurs and shadows are very broken in this flutter version)

Same thing, did you find any workaround for this or do I have to downgrade?

**Comment by Kamysek** [comment]
Having the same error

**Comment by AlexDochioiu** [comment]
> > Worth mentioning that I am on version: "7.8.1" because I am postponing the upgrade to flutter 3.13 (blurs and shadows are very broken in this flutter version)
> 
> Same thing, did you find any workaround for this or do I have to downgrade?

I personally just jumped to flutter 7.14-0.2 (beta) which solves many of the blur and shadow visual bugs. Note: I think backdrop filter blur still has an unusually big performance impact compared to flutter 7.10.

**Comment by JohnF17** [comment]
Hello @Milad-Akarie, This issue needs to be addressed, many don't want to upgrade to `Flutter 3.13+` due to many recorded bugs and performance issues so staying at `Flutter 3.10-` with `Auto_route 7.8.1` is our only option but this bug causes the app not to launch at all, kindly review this issue, thanks.

**Comment by Santa160** [comment]
Upgrade the flutter to latest version and error will be fixed. it worked with me

**Comment by Santa160** [comment]
> Getting the same build error too

Upgrade your flutter version

**Comment by Milad-Akarie** [comment]
@JohnF17 consider downgrading auto_route version then?

**Comment by JohnF17** [comment]
Hi @Milad-Akarie, as descibed on your [CHANGELOG](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/CHANGELOG.md)

> 7.8.2
> - HOTFIX: update sdk constrains to flutter: >=3.13.0 and dart: >=3.0.0 <4.0.0

It was only after `7.8.2` that dependency constraints were introduced for the new `flutter version >=3.13.0`.
So I had assumed `auto_route: 7.8.1` is the maximum version supported for `flutter versions <3.13.0`, so i thought it was fair to say since `7.8.1` had no issues with the previous versions it should have worked now just as well for people who haven't upgraded their flutter version for whatever reason.

But regardless, I have used FVM and upgraded both flutter and auto_route to their latest now and it works now 🎊, but if i do revert flutter back to 3.10, I guess I should use `auto_route: 7.8.0` 🤷‍♂️ and hope for the best.

Thanks for this great package! 🙏

**Comment by Mehmettmolla** [comment]
Hi @Santa160 , I found a way to use auto_route without using the current version of Flutter. Try these two package versions.
auto_route: ^6.4.0
auto_route_generator: ^6.2.0

**Comment by mateen-demah** [comment]
downgrading to auto_route 7.8.0 worked for me. I had the same problem as reported by @Santa160 .
In my case, I can't upgrade flutter because 3.13.x requires xcode 14 which I can't upgrade to.

**Comment by srdjan86** [comment]
Exactly as @mateen-demah  said, 7.8.0 works perfect with older version of flutter, just make sure to hard code the version value in pubspec.yaml as
auto_route: 7.8.0
