### ISSUE TITLE
Warning message when running: dart run build_runner build -d

### ISSUE THREAD

**Issue by VinhNgT** [Milad-Akarie/auto_route_library#1729]
When running dart run build_runner build -d, the following warning is shown:

```
[WARNING] build_resolvers:transitive_digests on lib/app_router.dart:
Unable to read asset, could not compute transitive deps: e_commerce|lib/app_router.gr.dart

This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
```

Is this normal and should I ignore this?

flutter: 3.13.3
auto_route: 7.8.3
auto_route_generator: 7.3.1
build_runner: 2.4.6

**Comment by Adwaithnow** [comment]
I resolved the warning related to build_resolvers. I have deleted auto generated route dart file and rerunning the build_runner, the warning was no longer present.

**Comment by VinhNgT** [comment]
> I resolved the warning related to build_resolvers. I have deleted auto generated route dart file and rerunning the build_runner, the warning was no longer present.

Yes, re-running build-runner won't trigger the warning. But it appears again every time the source file is changed

**Comment by rd-martin-jaeger** [comment]
Same here. 
Seems to be related to this [commit](https://github.com/dart-lang/build/commit/307a5aba8063fc236ba2de29ece0139108fd1b04). I'm still trying to understand and searching for a solution

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)

**Comment by eggp** [comment]
Same here and extra error:

Invalid argument(s): Missing library: package:..... :( 

environment:
  sdk: '>=3.1.2 <4.0.0'

dep:
  auto_route: 7.8.3
devDep:
  auto_route_generator: 7.3.1
  build_runner: 2.3.3 (and 2.4.6 same as)

**Comment by eggp** [comment]
I created reproduction repository:

https://github.com/eggp/auto_router_error

1. clone `main` branch
![2023-09-16_23-28](https://github.com/Milad-Akarie/auto_route_library/assets/1015211/41ed806f-799e-42b0-88ef-27dcbb0cf816)

reproduce:
1. flutter pub get
2. dart run build_runner build --delete-conflicting-outputs --verbose

rerun: dart run build_runner build --delete-conflicting-outputs --verbose
![2023-09-16_23-28_1](https://github.com/Milad-Akarie/auto_route_library/assets/1015211/6f5ad764-1935-4b0f-a1f2-ceaade99dacd)

---

2. clone `when_use_navigate_to_in_page_or_imported_reference` branch
![2023-09-16_23-33](https://github.com/Milad-Akarie/auto_route_library/assets/1015211/85117f6c-409d-4000-b9b7-93e8994d560f)

reproduce:
1. change branch: ....
2. delete .dart_tool directory (simulate clean install, because remove all cache!)
3. flutter pub get
4. dart run build_runner build --delete-conflicting-outputs --verbose

rerun: dart run build_runner build --delete-conflicting-outputs --verbose
![2023-09-16_23-34](https://github.com/Milad-Akarie/auto_route_library/assets/1015211/09544229-cd65-4ab8-9f07-4afc357e3d09)

---

## **summary:**
I could not simulate the error indicated in my previous comment, but I could simulate the error indicated by others.
It seems that if there is already a cache in the .dart_tool folder, the error does not appear until a code change induces it.
This would be fine in a local build environment, but in ci, for example, we generate the routes again, where the error occurs. Or even in a monorepo environment..., and this leads to even more special errors than mine: `Invalid argument(s): Missing library: package:...`

**Comment by eggp** [comment]
temporary solution: replace call named routing methods

**Comment by PawlikMichal25** [comment]
It's also happening in our project, however the generation fails. 
The log is super long and ends with:
```
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:265:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1777:22)
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1243:7)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2152:18)
<asynchronous suspension>
]
```

**Comment by Thioby** [comment]
add this to build.yaml


```
global_options:
  auto_route_generator:auto_router_generator:
    runs_before:
      - build_resolvers:transitive_digests
```

**Comment by Milad-Akarie** [comment]
@Thioby try updating to the latest auto_router_generator and see if you still go the issue?

**Comment by Thioby** [comment]
@Milad-Akarie works! This issue can be closed.
