### ISSUE TITLE
Use observers

### ISSUE THREAD

**Issue by alhafoudh** [Milad-Akarie/auto_route_library#21]
Is it possible to add observers? For example `HeroController()`?

**Comment by kuhnroyal** [comment]
There is no navigator involved in this library, you can just add the observers to your `Navigator`.

**Comment by Milad-Akarie** [comment]
@alhafoudh  by 'add' do you mean pass as a route parameter? because that's possible!
This has nothing to do with auto_route but if you're having troubles with your hero animation try using custom animations like fadeIn transition.

Hey, @kuhnroyal  I don't think he means observing the navigator itself. 
btw I'd like your feedback on my newly published package [injectable](https://github.com/Milad-Akarie/injectable)

**Comment by Milad-Akarie** [comment]
closing this for lack of solid use case
