### ISSUE TITLE
Unable to import custom transition in route.gr.dart file

### ISSUE THREAD

**Issue by mslalith** [Milad-Akarie/auto_route_library#233]
I'm using a `SharedAxisTransition` from `animations` package.
I've created a `Transitions` class and implemented the transitionsBuilder function with same signature.
The problem is that `Transitions` is unable to import in `route.gr.dart`.

`Undefined name 'Transitions'.`

I'm using it in a `CustomRoute`.
`CustomRoute(
    page: HomePage,
    transitionsBuilder: Transitions.sharedAxisHorizontal,
)`

**Comment by Milad-Akarie** [comment]
I'm not sure I understand. why would Transitions import route.gr.dart?

**Comment by munitum** [comment]
@Milad-Akarie I think what @mslalith is saying is that using your own custom transition functions does not currently work, because the library isn't able to correctly resolve the file containing the definitions of the custom functions. So the problem isn't importing router.gr.dart, it's that router.gr.dart doesn't have the import where the Transitions class is defined.

I've just run into this problem as well - I'd like to have write my own custom transitions, but they aren't imported correctly into the generated router file. I tried to poke around your code, but I wasn't able to find the problem with my limited understanding of what's going on.

If you have the time to take a look, I'm sure both of us (and many others) would greatly appreciate it. Thanks for your work on this awesome package! 😄

**Comment by softronaut** [comment]
I have same issue. I always get import error during normal development because of `build_runner` watch command.
A workaround is export your `CustomTransitions` Class with any `Route` you import inside `auto_router.gr.dart`.

```
export '../src/router/auto_route.dart';

class HomePage extends StatelessWidget {
...
```

**Comment by munitum** [comment]
@softronaut Nice and simple workaround (that I wish I'd thought of). Thanks!
