### ISSUE TITLE
Error on Nested route page refresh

### ISSUE THREAD

**Issue by zs-dima** [Milad-Akarie/auto_route_library#269]
in case of Flutter for Web, latest dev branch:

1. Page2 have some named parameter
2. Navigate to the Page2 page
3. Press refresh button 
4. we could see Error in log, then app redirected to the app root page.

Example:
```dart
@CustomAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(
      page: LoadingPage,
      initial: true,
    ),
    AutoRoute(
      page: HomePage,
      children: <AutoRoute>[
        AutoRoute(initial: true, page: Page1),
        AutoRoute(page: Page2),
        AutoRoute(page: Page3),
      ],
    ),
    //AutoRoute(path: '*', page: HomePage),
  ],
)
class $Router {}
```

Could be related to:
https://github.com/Milad-Akarie/auto_route_library/issues/251

**Comment by theBenForce** [comment]
I'm having the same issue.

**Comment by Milad-Akarie** [comment]
@zs-dima The current implementation turned out to have a lot of issues and bad behaviors when it comes to nested routing.
I'm actually re-writing the whole package to work with navigator 2.0 which is way too flexible and have a lot of potential. 
I could be patching this old mess or focusing on wrapping up the new auto_route?

**Comment by zs-dima** [comment]
I would prefer Navigator 2.0, hope it will not have this kind of issue

**Comment by theweiweiway** [comment]
Closing due to:
- AutoRoute 1.0 which solves this problem
