### ISSUE TITLE
How to pop() from screen with value

### ISSUE THREAD

**Issue by KieranLafferty** [Milad-Akarie/auto_route_library#295]
Using
AutoRoute 1.0.0-beta.3+1

On previous auto route I could call 

```
context.navigator.pop(<some_value>)
```
Now using AutoRouter via `AutoRouter.of(context).pop` there are no parameters available for passing on `pop()`. Should I still be using `ExtendedNavigator` or is `AutoRouter` the preferred method going forward? 

and define my route in router.dart as 

```
  MaterialRoute<SomeValueType>(
      path: '/some_path',
      page: SomeScreen,
    ),
```

Notice that now using AutoRoute it's unable to pass a value back. Am I using this wrong or is there a better way of doing this now?

**Comment by Milad-Akarie** [comment]
@KieranLafferty In our way to adapt to the new declarative way we had to let pop-completer go. 
This is how you can collect results from a route in auto_route 1.0.0

```dart
class MyTaskPage extends StatelessWidget{
// 
  final void Function(result) onResult;
  const MyTaskPage({Key key, this.onResult}) : super(key: key);
  ...
  
  /// when your done collecting your data
   onResult(data);
   context.router.pop();

}
```

pass onResult callBack to the route
```dart
router.push(MyTaskRoute(onResult:(result){
         // do Stuff with result;
   });
```

**Comment by KieranLafferty** [comment]
Ah great. I do wonder though how this may interfere with url string routing since you wouldn't be able to declare the `onResult ` for simple deeplink handling. If using callback functions is the preferred/only way to pass data back to the screen that pushes it does it make sense to have the generic type attached to `AutoRoute<T>`? I notice in it's implementation nit doesn't use the generic `T`

**Comment by KieranLafferty** [comment]
Would you consider me adding an extension on AutoRouter to add a `popWithValue()` to be an antipattern if it just delegates to  `Navigator.of(context).pop(<some_val>);` if the value is non null?

**Comment by KieranLafferty** [comment]
Just whipped this up to explain what I mean using code, haven't tested it just curious your thoughts on this approach in general

```
extension PopWithValue<T> on RoutingController {
  Future<T> popWithValue(T value) => value != null 
  ? Navigator.of(root.navigatorKey.currentContext).pop(value) 
  : pop().then((value) => null);
}
```

**Comment by edwardaux** [comment]
This is a very interesting one. I'm in the process of upgrading from `0.4` to `1.0` of auto_route (which has been quite the whirlwind ... haha) and ran into this very problem today. 

The suggestion that @KieranLafferty shared above seemed reasonable, but I think the problem extends beyond that to the call site. For example, when I push to a new screen that returns, say, a `User`, I really want to be able to do something like:
```
final user = await router.push<User>(SomeScreenRoute());
```
However, if I look at what happens when I push a route, I see:
```
abstract class StackRouter extends RoutingController with ChangeNotifier {
  Future<void> push(PageRouteInfo route, {OnNavigationFailure? onFailure});
  ...
}
```
`PageRouteInfo` is a generic class over `T`, however, it is not generified in the definition above, and the `push()` function always returns a `void`, not a `T`, so I can't see a way that an object can be returned using this mechanism.

I gather from @Milad-Akarie's comments above, this was a conscious decision in order to be able to support declarative routes, but as a consumer of the library, I'm genuinely considering whether the value I gain from the rest of auto_route is worth having to add callback functions to all my screens (not to mention that this pattern is a large step away from the standard Flutter pattern of being able to return values via `pop()`).

Don't get me wrong, I totally understand that sometimes decisions and trade-offs have to be made in order to support various features and I'm not suggesting that this particular decision is "wrong". For me personally, though, it is probably getting close to being a deal-breaker (not that I expect that one users' opinion should change everything... but I figure some polite feedback might be useful).

**Comment by Milad-Akarie** [comment]
Hey @edwardaux  add your vote here #432

**Comment by Milad-Akarie** [comment]
closing this in favor in #432
