### ISSUE TITLE
Initial deep link doesn't push all routes in parallel navigation

### ISSUE THREAD

**Issue by theweiweiway** [Milad-Akarie/auto_route_library#302]
Hi Milad,

I'm currently trying to get deep links working with parallel navigation. I've noticed that the app will open the correct path, however when I try to `pop()` it doesn't do anything. 

This is odd because I printed the `RootRouterDelegate.of(context).currentConfiguration` and it shows 3 routes in the history stack, yet I still can't `pop()`. Is this a problem of how I'm setting everything up, or maybe how deep linking works with parallel navigation?

Here is the full repository example:
https://github.com/theweiweiway/auto_route_example

Also some code if you don't want to dive into the whole repo first:
`main.dart`
```
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: _router.defaultRouteParser(),
      routerDelegate: _router.delegate(
        initialDeepLink: "/groups/details",
      ),
      builder: (_, router) {
        return router;
      },
    );
  }
```

Terminal after printing current config:
```
[
  Route{name: HomeRoute, path: /, params: {}}, 
  Route{name: GroupsFeature, path: groups, params: {}},
  Route{name: GroupsDetailsRoute, path: details, params: null}
]
```

Thanks!

**Comment by Milad-Akarie** [comment]
Hello @theweiweiway 
The problem is that empty paths are not included as prefixed matches.

The three routes you see is '/' this the home page which got a tabs router and tab routers don't pop so they pass priority to the parent and since the parent only got one page which is the home page then it won't pop 

Your setup has three nested controllers, each control either has only one page or is a tab controller which passes priority to parent or system navigator.

[/]____
           [group]____
                              [details]
               

I'm not sure if I should include empty paths when deep linking.

**Comment by theweiweiway** [comment]
Thanks for the quick reply @Milad-Akarie 

Thanks for the explanation - I kind of understand it. So to re-iterate, what you are saying is that:
I have 3 controllers:
1. [/] (which is the HomePage)
2. [groups]
3. [account] 

The HomePage controller is a tab controller which passes priority to [groups] or [account] controller based on whichever tab is currently selected.

When I deep link to `/groups/details` and then try to `pop()`, priority now goes to the [groups] controller which is the parent. However, what I am confused about now is that the [groups] parent controller has more than one page. It has `GroupsHomePage` (which is at /groups) and `GroupsDetailsPage` (which is at /groups/details). So I believe it should be able to pop from /groups/details back to /groups.

You were also saying empty paths are not included when deep linking. I tried changing my groupsRouter to
```
const groupsRouter = AutoRoute(
  path: 'groups',
  name: 'GroupsFeature',
  page: EmptyRouterPage,
  children: [
    RedirectRoute(path: "", redirectTo: "home"), // I tried with this line commented out as well
    AutoRoute(path: 'home', page: GroupsPage), // changed path here to "home" from ""
    AutoRoute(path: 'details', page: GroupsDetailsPage)
  ],
);
```

and deep linking to `/groups/home/details` but all I get is a blank page. When I deep link to `/groups/details` with this new configuration, it goes to the `GroupsDetailsPage` but doesn't allow me to pop still. 

Overall, when I have no deep link and I am at `/groups`, I can navigate to `/groups/details`. Then I can pop and go from `/groups/details` back to `/groups`. However, if i deep link directly to `/groups/details` it won't pop. I feel like deep linking should preserve the same behaviour as if you navigated to the page from the home page, which is why i was a bit confused.


OK thanks Milad. Also, I was wondering if you received the twitter and email message I sent you? I was trying to message you through github but it doesn't support private messaging

**Comment by Milad-Akarie** [comment]
AutoRoute supports same-level deep-linking because on mobile creating nested routers might be an over kill.
The following routes are on the same level (they're not nested) 
note: order is important - routes are matched from top to bottom.
'/'
'/products'
'/products/:id

given an  initialDeepLink `/products/1` all three routes above will be pushed.


so if you want `/groups/home/details` to work your setup should look like

```dart
const groupsRouter = AutoRoute(
  path: 'groups',
  name: 'GroupsFeature',
  page: EmptyRouterPage,
  children: [
    RedirectRoute(path: "", redirectTo: "home"), // I tried with this line commented out as well
    AutoRoute(path: 'home', page: GroupsPage), // changed path here to "home" from ""
     // this should include all previous segments
    AutoRoute(path: 'home/details', page: GroupsDetailsPage)
  ],
);
```
I'll study the possibility of matching empty paths when `inlcudingPrefixMatches` is set to true, so when GroupPage path is empty it will be included in the stack. 

I'm not on twitter, to busy to be lol
You can contact me on my gmail milad.akarie@gmail.com

**Comment by theweiweiway** [comment]
Hi Milad, sorry yes the `/groups/home/details` was my mistake. I forgot to make it
```
    AutoRoute(path: 'home/details', page: GroupsDetailsPage)
``` 

Now the initial deep linking works when i do `/groups/home/details`!

For now, i have a way of doing it - ultimately, the empty path would be best since it's cleaner and more intuitive, especially in a web browser. But I can definitely work with the current solution!

Thanks again!
