### ISSUE TITLE
Some questions about AutoRoute 2.0

### ISSUE THREAD

**Issue by aytunch** [Milad-Akarie/auto_route_library#333]
I ran into several issues after migrating to version 2. I listed them below. I would be glad if you could help me with these @Milad-Akarie 

My RouteObserver prints the below log:

> _PageBasedMaterialPageRoute(MaterialPageX("null", null, null), animation: AnimationController#08c74(:arrow_forward: 0.000; for _PageBasedMaterialPageRoute(null)))

As you can see the arguments are all null and not very informative. Also when I'm trying to use `popUntil`, I cannot use a predicate since the route's settings name is null, and the type of the route is `_PageBasedMaterialPageRoute`. Therefore I'm having trouble finding a way to write this predicate.

Let's say my navigation stack is currently a-b-c-d
and I want to pop from d until a so i call `popUntil()`
This popUntil shows the middle pages b and c. Is there a way to directly popUntil a without seeing and initing the middle pages?

I looked at the implementations and `.popUntil` uses the default navigator `popUntil` whereas `.navigate` is using `_removeLast`. Is there a reason for the implementation difference?

When I use `.replace(MainRoute)`, a new `MainPage` gets created and pushed. Is there a way to re-use the one which was already in the stack?

Finally, it would be great if there was a migration guide or some documentation, or at least more descriptive comments in the source code.

Thanks.

**Comment by Milad-Akarie** [comment]
Hey @aytunch  I've been really swamped lately but I'm planning on resuming work on auto_route soon.

remove vs pop in short...
remove* -> will only work on AutoRoutePages that's managed by the `StackRouter` and can not be intercepted by WillPop scopes,  mutates the stack inside of `StackRouter`
pop* -> works on page and pageless routes (including dialogs and bottomSheetModels)  and can be intercepted by WillPop scopes, mutates the stack inside of Navigator which will mutate the stack inside of `StackRouter` in `onPopPage`,


until recent raised issues I was under the impression that the native `popUntil` is not going to be needed but turns out I'm wrong, in the next build I'll work on fixing that and provide a simpler way to use predicates that handle AutoRoutePages.


you could use this code as a reference until the next build

```dart
  AutoRouter.of(context).popUntil((route) {
       if(route.settings is AutoRoutePage){
          // it's a page route
         (route.settings as AutoRoutePage).routeData.name;
       }else{
         // it's a pageless rout (dialog or bottomSheetModel ..etc)
       }
      return false;
    });

```

I'm not sure I understand your question about `replace` but he way `replace` is meant to work is pop the current route(top route in stack) and push the provided route.

**Comment by theweiweiway** [comment]
Closing due to stale issue. 

@aytunch please re-open if you feel that it's necessary
