### ISSUE TITLE
Fullscreen dialog underneath bottom navigation bar

### ISSUE THREAD

**Issue by Herrera93** [Milad-Akarie/auto_route_library#366]
Would it be possible to have fullscreen dialog appear over the bottom navigation instead of underneath?
For example if I add `fullscreenDialog: true` to `BookDetailPage` in the example app it appears underneath bottom navigation bar.

**Comment by theweiweiway** [comment]
@Herrera93 You can listen for the current route and only show the bottom navigation bar on certain routes:

You can get the current path like so:
```
  String path = ""; 

  @override
  void didChangeDependencies() {
    var rootDelegate = RootRouterDelegate.of(context);
    rootDelegate.addListener(() {
      if (rootDelegate?.currentConfiguration != null) {
        final newPath = rootDelegate.currentConfiguration.map((a) {
          if (a.path.isNotEmpty && !a.path.contains("/")) {
            return '/' + a.path;
          }
          return "";
        }).join("");
        setState(() {
          path = newPath;
        });
      }
    });

    super.didChangeDependencies();
  }
```

Now, you can add something like this in your `AutoTabsRouter`:
```
          bottomNavigationBar: path == '/groups/root' || path == '/account/root'
              ? buildBottomNavigationBar(tabsRouter)
              : null,
`` `

**Comment by theweiweiway** [comment]
It's now much easier to get the current path!
`AutoRouterDelegate.of(context).urlState;`

Please close if this solution works for you

**Comment by Herrera93** [comment]
@theweiweiway that's a good solution and one the would solve this, I end it up having my fullscreen dialog at the root level so they'll be shown above everything. 
I'll close this since your solution solves it as well

**Comment by maxiundtesa** [comment]
> It's now much easier to get the current path!
> `AutoRouterDelegate.of(context).urlState;`
> 
> Please close if this solution works for you

@theweiweiway Is there something similar to get the next (full) path thats already getting created inside the builder method of the AutoTabsRouter Widget? To get the new route that was just pushed to the router? 
Because in that case, i could prevent building the bottom navigation bar for certain routes.

`AutoRouterDelegate.of(context).urlState` is unfortunately no help for that case, because it returns the url of the currently visible route/url, not the one that will be shown in 10ms.
