### ISSUE TITLE
web: persist route state with browser refresh

### ISSUE THREAD

**Issue by idraper** [Milad-Akarie/auto_route_library#408]
When a user refreshes the page, the current named route does not stay. This didn't happen prior to updating to flutter 2.0.0 since it only used named routes, where now auto_route uses delegates.

The desired behavior is if I am at URL (eg `http://localhost:54047/#/some_path/more_path`) then it will stay on that view when the user refreshes the page.

**Comment by CassiusPacheco** [comment]
I can replicate this issue [here](https://flutter-web-deploy.herokuapp.com/#/home). Going to the detail screen and refreshing makes the router lose the back button. Tapping on the browser's back button makes it go back to home, but in a strange way, instead of popping it presents a new screen (pay attention to the animation).

Reseting the state by typing in the home url manually `https://flutter-web-deploy.herokuapp.com`, then going to details and back works as expected. Just the refreshing that breaks the navigation.

**Comment by Milad-Akarie** [comment]
@CassiusPacheco Refreshing means rebuilding the whole App with the url in the browser bar as an initial path. 
 I believe that's an expected/acceptable behavior when it comes to web? no? 
 unless of-course backed with state restoration implementation which I haven't time to experience on yet.

**Comment by CassiusPacheco** [comment]
I agree that the current page's state is lost on reload, however, losing the entire history of pagination upon reload is not how websites behave. If you go to the link I mentioned above, click on go to detail page and reload, you'll see straight away how the app's back button is gone, meaning the whole stack was destroyed. Then using the browser's back button causes the previous screen to be PUSH instead of popping the current one. The entire navigation becomes weird upon reload.

I imagine this might be hard to fix, however I'm raising the issue since it doesn't seem to be the expected routing behaviour.

**Comment by idraper** [comment]
For the initial issue created, the main problem isn't that the stack is being destroyed. The main problem is that if you enter a named route (eg `http://localhost:54047/#/some_path/more_path`) then it doesn't care about the named route - it always uses the initial path. so if I enter the named route above, it still takes me to `http://localhost:54047/#/main`, where `main` is the initial path entered.

**Comment by theweiweiway** [comment]
@idraper hey, is your initial path matching problem related to #392 ?

**Comment by Milad-Akarie** [comment]
@idraper are you passing an initial destination to root router delegate?

**Comment by Milad-Akarie** [comment]
@CassiusPacheco When you tap the browser's back button it might seem like you're popping the current page but you're actually pushing a new path ( the entry below current in the browser stack ) but because the page we're pushing have the same key as the one in stack the Navigator can update it.

**Comment by idraper** [comment]
> @idraper hey, is your initial path matching problem related to #392 ?

I don't think so, because I'm not using any nested routes, here is an example of what I am doing:

```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    MaterialRoute(page: pages.Main, initial: true, path: '/main'),
    MaterialRoute(page: pages.SomePage, path: '/some_path'),
  ],
)
class $Router {}
```

> @idraper are you passing an initial destination to the root delegate?

Yes, if you look at the snippet above, that is my code for the router, then below I have where I use it. The only difference is that I have more pages (and obv some different names).

```
MaterialApp.router(
  title: 'TestApp',
  theme: myTheme,
  routerDelegate: router.delegate(initialRoutes: [routing.MainRoute()]),
  routeInformationParser: router.defaultRouteParser(),
)
```

After some testing, if I remove the `initialRoutes` argument from the delegate the issue no longer occurs. However, this causes a new problem where going to a base path (eg `http://localhost:54047/#/`) no longer goes to the default path (main) - it instead throws an error since it cannot find the path (I don't want one for `/`). The excepted behavior would be to have `http://localhost:54047/#/` immediately route to `http://localhost:54047/#/main` (the initial path). Shouldn't this occur since in the `MaterialRoute` I have the `initial: true` argument set for `/main`?

**Comment by maxiundtesa** [comment]
I'll agree with @CassiusPacheco about the expected behavior. If the user reloads a page, he would expect that the previous routing stack would stay the same. This is the case if just the browser buttons are used for navigation. 

However due to the nature of flutter, almost all flutter web apps also have a mobile application and therefore probably also feature in-app navigation, because it is needed on these platforms. 
Because of that it is really confusing for the user if he normally has on-screen navigation on the webpage, then reloads the application/website and afterwards the buttons are gone. Maybe the solution could be something like " for a nested page the parent pages are automatically build on reload and added to the stack"

**Comment by ntminhdn** [comment]
@idraper @CassiusPacheco @maxiundtesa @Milad-Akarie I am facing this issue when I develop a website on mobile. Any solution for this issue?

**Comment by bartekpacia** [comment]
I'm having the same issue. I don't have much experience with Navigator 2.0, but it seems like this shouldn't happen (i.e URL should not be reset on browser refresh).

**Comment by Vladeouz** [comment]
any solution for this ?

**Comment by arslan-charyyev** [comment]
For anyone seeking solution to this issue I can offer the following advice:

While it is theoretically possible to manually serialize to persistent storage the page stack whenever it changes (for example via a [navigation observer](https://pub.dev/packages/auto_route#navigation-observers)) and restore it, in practice it may be quite challenging, especially considering the nested routes.

However, if the goal is to have a functioning app with a good enough back-navigation behavior after a page reload, then it can be easily achieved with the help of existing features of the library by a combination of path/query parameters and deep links.

Firstly, you have to restrict your screen/page constructor parameter types to `String` or something that can be easily serialized to string, like integer or boolean. Luckily this is easily achievable because most of the time you will be passing IDs for routes like `/details/:id`. Then you have to annotate those constructor parameters with path/query annotations as described in the [working with paths](https://pub.dev/packages/auto_route#working-with-paths) section of the documentation.

Secondly, you have to carefully construct your route tree such that the library can rebuild the stack from a liner route list as described in [this section](https://pub.dev/packages/auto_route#deep-linking-to-non-nested-routes) of documentation. Pay attention to the `includePrefixMatches` parameter, which has to be enabled for this to work on the web platform.

If you carefully follow the above-mentioned rules, then after reloading the page on the web, the library will build the route stack that corresponds to the URL path and things like popping the route or in-app back navigation will work as expected. Of course this is not the same fully restoring the state, but at least it keeps the application in a functioning state, where all the back buttons are present and working as expected.

**Comment by Milad-Akarie** [comment]
@arslan-charyyev I could't have explained better.

**Comment by Vladeouz** [comment]
> For anyone seeking solution to this issue I can offer the following advice:
> 
> While it is theoretically possible to manually serialize to persistent storage the page stack whenever it changes (for example via a [navigation observer](https://pub.dev/packages/auto_route#navigation-observers)) and restore it, in practice it may be quite challenging, especially considering the nested routes.
> 
> However, if the goal is to have a functioning app with a good enough back-navigation behavior after a page reload, then it can be easily achieved with the help of existing features of the library by a combination of path/query parameters and deep links.
> 
> Firstly, you have to restrict your screen/page constructor parameter types to `String` or something that can be easily serialized to string, like integer or boolean. Luckily this is easily achievable because most of the time you will be passing IDs for routes like `/details/:id`. Then you have to annotate those constructor parameters with path/query annotations as described in the [working with paths](https://pub.dev/packages/auto_route#working-with-paths) section of the documentation.
> 
> Secondly, you have to carefully construct your route tree such that the library can rebuild the stack from a liner route list as described in [this section](https://pub.dev/packages/auto_route#deep-linking-to-non-nested-routes) of documentation. Pay attention to the `includePrefixMatches` parameter, which has to be enabled for this to work on the web platform.
> 
> If you carefully follow the above-mentioned rules, then after reloading the page on the web, the library will build the route stack that corresponds to the URL path and things like popping the route or in-app back navigation will work as expected. Of course this is not the same fully restoring the state, but at least it keeps the application in a functioning state, where all the back buttons are present and working as expected.

oh okay. so its about the deeplink isnt it ?, it will be great if we get some video explanation about it. But again, thank you for your explanation.
