### ISSUE TITLE
Passing data back from screen

### ISSUE THREAD

**Issue by haashem** [Milad-Akarie/auto_route_library#432]
I'm migrating my code to use AutoRoute, but it seem this library doesn't support passing data back:

```final editedStore = await AutoRouter.of(context).push(const EditStorePageRoute());```

push returns `Future<void>` but I'm expecting to be `Future<T>`

am I missing something or its not supported yet?

**Comment by UliPrantz** [comment]
I believe currently this isn't supported (they bypass this with callback functions which are passed between screens - at least this is how it looks like in the docs). But I also would like to have this ability since I believe passing callbacks around reduces readability and probably it reduces performance when the callback function triggers unnecessary rebuilds.

The way it's handled in the native flutter navigator (which is the way @haashem described) is pretty close to perfect in my opinion. I would like to hear the arguments why it isn't supported in auto_route.

**Comment by Milad-Akarie** [comment]
Hello @haashem @UliPrantz, Awaiting results was ditched in favor of callback function to move closer to support declarative navigation, right now auto_route partly supports declarative navigation where the only way you can get results back is by passing a callback function. 

I'm willing to try supporting awaited results again if a decent number of auto_route users vote for it.

**Comment by haashem** [comment]
Thanks @Milad-Akarie for giving back to Flutter community,
May you explain what’s declarative navigation?

passing closure for receiving data back is strange in Flutter. and I see it complicates returning data. (In Swift I use closure for passing data back because there is no ‘async await’ keywords)

So to become good Flutter citizen, I prefer the default one because it’s much easier to read and understand.

**Comment by Milad-Akarie** [comment]
Hey @haashem in short instead of pushing or replacing routes you pass them to a widget 

```dart
body: AutoRouter.declarative(onGenerateRoutes: (_, __) {
      return [
          BookListRoute(
            onBookSelected: (book) {
              setState((){
                _selectedBook = book;
              }),
          ),
        if (_selectedBook != null)
          BookDetailsRoute(
            book: _selectedBook,
          ),
      ];
    }, 
```
as you can see we're just passing pages to the router based on the state and we're not using any imperative navigation using push,replace or friends. 
and that's how flutter in general is meant to work (declaratively)

**Comment by haashem** [comment]
Brilliant, I have not seen this example in documentation. may you hint about declarative navigation in read me? and a sample code also.

HomePage body is BookListPage, on book selection navigates to BookDetailsPage.
from above code it's not clear navigation is push or replacement.

**Comment by edwardaux** [comment]
Thanks for the pointer to this issue @Milad-Akarie ... your comment and example above triggered me to finally get around to reading about [Flutter Navigation 2.0](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit) and ... wow, just wow ... 

I've just spent the past few days poring over unbelievably complicated hello world examples and Medium articles where people try to explain how to use this new navigation style.

For sure, I can see some use cases where the new style offers a bunch of capability that the old way didn't but, for me personally, it feels like they've created an extremely complicated API that sacrifices the 90% of use cases in order to provide support for the 10% of use cases.

I've seen a lot of people saying that it should be referred to as "Advanced Navigation" rather than "Navigation 2.0" (which implies that 1.0 is obsolete), and this resonates quite well with me personally.  

Given that one of the stated goals in the official Flutter doc I linked above is for the imperative and declarative APIs to co-exist, it feels like routing libraries like this one have a decision to make about which way they're going or whether they're intending to support both.

I need to actually implement the new declarative API in a real project before I make final judgement, but from the dozens of articles I've read so far, everything suggests that the purported benefits are not even close to outweighing the additional complexity it introduces - for the types of apps I'm writing anyway. 

Anyway, this is a long-winded way of saying that I would love it if auto_route was able to continue to support the imperative style of pushing and popping (including returning values). Consider this post a verbose +1 😂

**Comment by bounty1342** [comment]
Hi,

This callback method is not very straitForward to use with for ex showDialog and other flutter widgets.
Is there a way to call Navigator.pop(context, T) and then update Autoroute Stack ?

That would be a nice way to overcome this in the meantime.

Regards

**Comment by 2shrestha22** [comment]
Yes it will be nice having awaited results again. It makes things easier and straight. Thank you the for awesome package.

**Comment by jlnrrg** [comment]
With the new update 2.0 it is now possible to pop data back.
The documentation is on the way, as far as I heard, but for the impatient people here is how you can do it:

In your router config specify which data type is returned.
e.g.: (here a Set<User> is returned)

```dart
AutoRoute<Set<User>>(
                      page: UserSelectPage,
                    ),
```

In your Page, you have to pop the values:

```dart
onPressed: () async {
          await AutoRouter.of(context).pop(yourValues);
        },
```

Then in your code you can call this to push the page and work with the return value.

```dart
onPressed: () async {
              final Set<User>? users = await AutoRouter.of(context)
                  .push<Set<User>>(
                      UserSelectPageRoute());
              if (users != null) {
                await doOtherStuffWithYourNewData(users);
              }
            }
```

**Comment by anushka-mim** [comment]
@Milad-Akarie 
As of 7.9.2, the pop method is deprecated. 
In an app that has multiple pop methods already in use, some that pass data back, what would be the preferred way of refactoring this code? Is `maybePop` safe enough to be used as a replacement?

**Comment by Milad-Akarie** [comment]
@anushka-mim pop was just renamed to maybe pop, the functionality is still the same
