### ISSUE TITLE
Master Detail

### ISSUE THREAD

**Issue by slecoustre** [Milad-Akarie/auto_route_library#465]
Hello

I would like to make a Master/Detail application.
When I'm on mobile I want to make a push to go from the list to the detail. But when I am on tablet to have the list on the left and the detail on the right.

But I don't see how to build my router with AutoRoute.

Is this possible?

Thank you for your help

**Comment by theweiweiway** [comment]
I'm not 100% familiar with `LayoutBuilder`, but you could use that widget to figure out what to render. On small screen size, show just List. On large screen size, show List + Detail on right side.

OK, so that handles the rendering, which is the easy part. Onto the routing...

Set up your router with 2 routes like so:   
```
AutoRoute(path: "/master", page: MasterPage),
AutoRoute(path: "/detail", page: DetailPage),
```

**Now on small screen size:**
Start at the path `/master`. This renders the master list.
When you click on a list item, push into the detail page with `context.router.push(DetailRoute)`. This is intuitive and simple.

**Now on large screen size:**
Render master list on left side. Render nothing on the right side if no item is selected. If you click on a detail item, render the right side detail. 

No need to push another route or do anything. Everything takes place in `/master` for the large screen size. 

If you want, you could get fancy with query parameters. For example, if the route was `/master?detail=69` then you could set the right side detail component to open with the item that corresponds to 69 oh yeah. 

In any case, for large screen size, you don't need to use the `/details` route. You can have it in your router, but it just won't be used.

**Comment by theweiweiway** [comment]
@slecoustre please close if this answered your question, thanks
