### ISSUE TITLE
How to navigate without context?

### ISSUE THREAD

**Issue by carlosfiori** [Milad-Akarie/auto_route_library#495]
In previous versions was possible to navigate to pages without using context, it's possible now or there plans to add this in future?

**Comment by Milad-Akarie** [comment]
@carlosfiori  you could either use the generated router as a global variable or injected using get_it or such

**Comment by saswatsaubhagya** [comment]
some please add some example

**Comment by mirkancal** [comment]
I'm trying to show a miniplayer, I already did it before with a navigationservice, locator and navigator key combination. Right now I'm using MateraialApp.router constructor from this package, instead of the regular one. I can't give the navigatorKey on MaterialApp.router. Looking for ways to get context inside this service.

**Comment by qscr** [comment]
> I'm trying to show a miniplayer, I already did it before with a navigationservice, locator and navigator key combination. Right now I'm using MateraialApp.router constructor from this package, instead of the regular one. I can't give the navigatorKey on MaterialApp.router. Looking for ways to get context inside this service.

are you solved this?
