### ISSUE TITLE
AutoRouteGuard resolver.next() triggers rebuild

### ISSUE THREAD

**Issue by FaFre** [Milad-Akarie/auto_route_library#553]
I have the problem that after migrating to 2.x, `AutoRouteGuard` is triggering a rebuild of the pushed sign-in/authentication page during the new `resolver.next()`. This results into a second call of the onComplete()-callback. For 1.x this was not the case.

I created a fully working sample here: https://github.com/FaFre/auto_route_guard_bug

I validated this issue with both Linux native and Chrome. It's best tested with Chrome, calling directly the /login route results in the following output:
```
Build SignIn
Loading
Build SignIn
Has Data
```
The route pushed through the AutoRouteGuard will result in the following output:
```
Build SignIn
Loading
Build SignIn
Has Data
Build SignIn
Has Data

════════ Exception caught by scheduler library ═════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: Future already completed

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/async/future_impl.dart 45:79                                     complete
packages/auto_route/src/auto_route_guard.dart 37:18                           next
packages/auto_route_guard_bug/auth_guard.dart 10:17                           <fn>
packages/auto_route_guard_bug/sign_in_page.dart 21:23                         <fn>
...
════════════════════════════════════════════════════════════════════════════════
Build SignIn
Has Data

════════ Exception caught by scheduler library ═════════════════════════════════
Bad state: Future already completed
════════════════════════════════════════════════════════════════════════════════

```

I'm not sure if this is a bug, or if it's required to find a new way handling this in 2.x. For 1.x this just worked perfectly.

**Comment by Milad-Akarie** [comment]
Hello @FaFre actually this has nothing to do with the guard. `Navigator` will trigger a rebuild on the route being removed from the stack with it's status set to `disabled` (isActive = false )  for transition proposes ( I think ) so you end up calling `onComplete` twice and that's what's causing the error. 
I think what would work is calling onComplete inside of a listener or some place that's guaranteed to be called only once instead of putting inside of the build function.  
if you have to keep your logic inside of the build function for some reason, you should check weather the route is still active before calling `onComplete` e.g


```dart
// only call onComplete if this's is most top page in stack
  if (context.routeData.isActive)
          WidgetsBinding.instance?.addPostFrameCallback((duration) {
            onComplete?.call();
          });
```

**Comment by FaFre** [comment]
Thank you so much @Milad-Akarie ! With that check it's working like a charm now.
If you think it makes sense to somehow use the code as an example, feel free to do so :)
