### ISSUE TITLE
parent route rebuilt on replacing child

### ISSUE THREAD

**Issue by ayushin** [Milad-Akarie/auto_route_library#624]
```
        AutoRoute(
          path: 'reports/:id',
          page: ReportWrapperPage,
          name: 'ReportRouter',
          children: [
            AutoRoute(path: '', page: ReportListViewPage),
            AutoRoute(path: 'cards', page: ReportCardViewPage),
          ],
        ),
```
when I navigate to `/reports/:id` the ReportWrapperPage widget is created twice and also when I navigate to a child page.

Is this a normal behaviour and how can I prevent this from happening?

**Comment by ayushin** [comment]
it seems like it is undocumented behaviuor when the constructor is not a `const` constructor ...

**Comment by Milad-Akarie** [comment]
@ayushin  why would you want to prevent a rebuild from happening? just make sure you're not making any state changes inside of your build function as it maybe called many times which is a really cheap operation for flutter. 
for AutoRoute it's needed because for example if the Parent page have a back button ( pop button) and it needs to to be hidden or shown depending on the child stack's count. 
 closing this for now, please reopen if you have more questions
