### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by idkq** [Milad-Akarie/auto_route_library#629]
When running "flutter packages pub run build_runner build"

```
QueryParams must be nullable or have default value
package:example/mobile/screens/profile/my_books_page.dart:7:43
  ╷
7 │   MyBooksPage({Key? key, @queryParam this.filter = 'none'}) : super(key: key) {
  │                                           ^^^^^^
  ╵
```

**Comment by dfdgsdfg** [comment]
https://github.com/Milad-Akarie/auto_route_library/issues/404

**Comment by Threehair** [comment]
Same problem here. I wanted to learn auto_route from the given example (since the docs are really insufficient), but the example just does not work, and I do not know how to fix it to make it runnable. Does Milad or anybody else has some time and willingness to fix it? BTW, I love this package, but I cannot use it to its full potential. Not enough docs for beginners-to-intermediates.

**Comment by Milad-Akarie** [comment]
@Threehair working on a new build + more docs

**Comment by Threehair** [comment]
Actually I think, https://autoroute.vercel.app is a pretty good start but needs to be expanded. I am not sure if the content is on github.
Is there a process for suggesting edits to these docs in case users find any potential issues (typos, etc.)?
