### ISSUE TITLE
Transition animation

### ISSUE THREAD

**Issue by adamsmaka** [Milad-Akarie/auto_route_library#633]
How to turn off animations? It looks bad on web apps when we animate transitions like push and pop on mobile.

**Comment by bounty1342** [comment]
https://autoroute.vercel.app/basics/page_transitions

> "If you don't want any transitions, use CustomRoute and leave transitionsBuilder to be empty"

**Comment by Milad-Akarie** [comment]
@adamsmaka use `CustomAutoRouter` and pass your desired transition to transitionsBuilder or pass nothing if you want no translation. 

you can also use CustomRoute instead of AutoRoute to have different trans for different routes as @bounty1342 said. 

use AdaptiveAutoRoute if your App supports both mobile and web.
