### ISSUE TITLE
pushAndPopUntil() should be pushAndRemoveUntil()

### ISSUE THREAD

**Issue by dfdgsdfg** [Milad-Akarie/auto_route_library#643]
`pushAndPopUntil()` fires `push().then()` block of parent's route.

Maybe it is intended behavior, but it is an odd and really not a useful scenario IMO.

It should be `pushAndRemoveUntil()` which is not fire `push().then()` block.

```dart
// RootPage
router.push(ParentRoute()).then((_) {
  print('hello');
});

// ParentPage
router.push(ChildRoute());

// ChildPage
// Push HomeRoute expectely but also oddly RootPage's then block also evalutated
router.pushAndPopUntil(HomeRoute(), predicate: (route) => route.isFirst);  //  ---- hello printed
```

**Comment by Milad-Akarie** [comment]
@dfdgsdfg  yes, it is an expected behavior by the native navigator's popUntil action, in older versions I tried implementing the pushAndRemoveUntil functionality but it didn't work as I had to report back the removed routes one by one to the navigator and that didn't look pretty. 

perhaps you can achieve your goal by using ` navigate(const HomeRoute()) ` if you'r sure your `HomeRoute` is already in the stack or `replaceAll(const [HomeRoute()])`
