### ISSUE TITLE
Generic nested routing

### ISSUE THREAD

**Issue by benjaminschreck** [Milad-Akarie/auto_route_library#696]
I would like to archive a structure that looks something like this: 
```
AutoRoute(
  page: CurrentCompanyPage,
  children: [
    AutoRoute(
      page: UserManagementPage,
    ),
    AutoRoute(
      page: CompanyManagementPage,
      children: [
        AutoRoute(
          page: CurrentCompanyPage,
          children: [
            AutoRoute(
              page: UserManagementPage,
            ),
            AutoRoute(
              page: CompanyManagementPage,
              children: [
                //again CurrentCompanyPage and so on
              ],
            ),
          ],
        )
      ],
    ),
  ],
)
```

The problem is that I don't know how deep this will be. As a workaround I could just copy paste it 10 times, but that is obviously not a long term solution. 
Is there a way to archieve a reusable CurrentCompanyRoute?  

For example: 
 ```
AutoRoute(
  page: CurrentCompanyPage,
  children: [
    AutoRoute(
      page: UserManagementPage,
    ),
    AutoRoute(
      page: CompanyManagementPage,
      children: [
        RecursiveAutoRoute(
          page: CurrentCompanyPage,
          maximumDeepness: 10,
        ),
      ],
    ),
  ],
)
```

**Comment by craigomac** [comment]
Same question here—an even simpler use case you can imagine is that you have some screen representing a product, and at the bottom is a list of similar products, which themselves link to other products etc. etc.

Ultimately you might have hundreds of pages in the navigation stack. Ideally we should also be able to build a URL from that, like `product/23/related-product/25/related-product/27/related-product/30`. For websites this would clearly be nuts—and unnecessary since you have browser history—but in apps it's a common scenario.

**Comment by benjaminschreck** [comment]
I'm not sure if this is the same use case. My described use case could be compared to a nested folder structure where subfolders can be added to subfolders. 
In the UI the parent Company is needed to show the relation. It isn't my goal to show the navigation history in the URL.
