### ISSUE TITLE
Duplicate route names must have the same path

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/auto_route_library#706]
Hey,
I'm migrating from a different package, I really like the overall stability and fluidity of this package, Well done!
I stumbled into an issue, I have the same route configured multiple times, one is in the root and another is in a nested route.
However I get this error `Duplicate route names must have the same path!`, because I set the root route with a slash in the beginning and the other one without slash (because it doesn't let me - throws this error `Child can not start with a forward slash`)

I need the root route to start with slash because deep links won't work if there is no slash.

This is the setup:
```
@MaterialAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: <AutoRoute>[
 AutoRoute(
      path: '/post',
      name: 'PostRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(path: ':postId', page: PostView, initial: true),
      ],
    ),
AutoRoute(
  path: 'user',
  name: 'UserRouter',
  page: EmptyRouterPage,
  children: [
    AutoRoute(
      path: ':username',
      name: 'UserRoute',
      page: ProfileView,
      initial: true,
    ),
    AutoRoute(
      path: 'post',
      name: 'PostRouter',
      page: EmptyRouterPage,
      children: [
        AutoRoute(path: ':postId', page: PostView, initial: true),
      ],
    ),
  ],
)])
```

There could be two different solutions
1. Allow root routes to have a slash in the start and check for equality of the path without the slash, so `/post` will be equal to `post`.
2. Allow nested routes to start with slash 

Please help,
Thanks

**Comment by Milad-Akarie** [comment]
Hello @naamapps and welcome to auto route, think of generated route objects as named locations of your App, two locations can have the same name if the have the same path/segment regardless of their parent/base path.

Your issue can be fixed by simply renaming the poster router inside of user router to something like UserPosterRouter.

And by the way of you're nesting all of these routers just to have deep linking in your App you should know that autoRoute supports sibling deep-linking, not sure that's the best way to describe it but this is how it works

Lets say we have two sibling paths, one to display a lists of posts and another to display single post details

/posts
/posts/:id

Setting the intialDeepLink to posts/1 will add both routes to the stack

**Comment by naamapps** [comment]
Thanks for your reply @Milad-Akarie,
I did try to rename to UserPostRoute, but this will create a new route object, and I would like to push with the same object across my application to keep simplicity. 
For example if I'm in a root route and push PostRoute, it will push in the root, and if I'm in a nested route I will need to check the context of the navigation to know which route object to use. This will add complexity I would like to avoid.

I'm not sure what you mean with sibling deep linking.
I am nesting my routes for deep linking and to have a persistent bottom nav bar. 
So I have the user Route registered multiple times and also the post route, each registered in the root and in all routes that have children (that are relevant).

I couldn't find something similar in the docs, it would be great if you could show me an example if there is something better to be done.

Nevertheless, I really think you should consider maybe at least allowing child routes to have slashes. Because this setup works well, just the deep links doesn't work.
I just need that both routes will have the same name.

**Comment by Shahmirzali-Huseynov** [comment]
> 

@naamapps how did you solve? can you give example, unfortunately I didn't understand.
