### ISSUE TITLE
Popping a dialog will pop the page but not the dialog

### ISSUE THREAD

**Issue by yamamz** [Milad-Akarie/auto_route_library#772]
```
 return await showDialog<bool>(
      context: context,
      barrierDismissible: barrierDismissible,
      useRootNavigator: useRootNavigator,
      builder: (BuildContext context) {
        return AlertDialog(
            title: Text(
              title!,
              style: TextStyle(
                  color: Theme.of(context).primaryColor,
                  fontWeight: FontWeight.bold),
            ),
            content: Wrap(
              children: [
                Text(
                  body!,
                  style: textTheme.bodyText2,
                ),
              ],
            ),
            actions: <Widget>[
              TextButton(
                child: Text(positive,
                    style: TextStyle(
                        color: Theme.of(context).primaryColor,
                        fontWeight: FontWeight.bold)),
                onPressed: () {
                  Navigator.of(context).pop(false);
                  if (onPressPostive != null) {
                    onPressPostive();
                  }
                },
              ),
            ],
          ),
        );
      },
    ); return await showDialog<bool>(
      context: context,
      barrierDismissible: barrierDismissible,
      useRootNavigator: useRootNavigator,
      builder: (BuildContext context) {
        return PointerInterceptor(
          child: AlertDialog(
            title: Text(
              title!,
              style: TextStyle(
                  color: Theme.of(context).primaryColor,
                  fontWeight: FontWeight.bold),
            ),
            content: Wrap(
              children: [
                Text(
                  body!,
                  style: textTheme.bodyText2,
                ),
              ],
            ),
            actions: <Widget>[
              TextButton(
                child: Text(positive,
                    style: TextStyle(
                        color: Theme.of(context).primaryColor,
                        fontWeight: FontWeight.bold)),
                onPressed: () {
                  Navigator.of(context).pop(false);
                  if (onPressPostive != null) {
                    onPressPostive();
                  }
                },
              ),
            ],
        
        );
      },
    );
```

**Comment by mpiparo** [comment]
Facing similar issue, but in my case I am launching the dialog immediately when the page finishes building. I noticed odd behavior in some cases when looking at the _history in the Navigator, specifically when using 'context.router.replace(...)' to navigate my page. The dialog route was not always in the _history, only my page route, so the pop was popping my page and not the dialog.

I'm not exactly sure if the replace is possibly updating the nav _history after the dialog is launched, but I do know that if I put a 500ms delay before launching the dialog, everything looks ok, the _history has my page and dialog on top. Also, when I tried to nav to my page with a 'push' instead of 'replace', it looked ok as well. 

Not sure if that's very helpful, but just some observations I noticed.

**Comment by yamamz** [comment]
I add some delay when  launching a dialog. sometimes it works sometimes won't. I will your other suggestions thank you.

**Comment by mpiparo** [comment]
From what I can tell it's a timing issue between navigating to the route and when the dialog is added to the nav stack. If I nav to my page with a 'replace' or a 'pushAndPopUntil' method for example, and add the dialog too quickly (in my case I'm using a Bloc listener on very basic splash page, so the page builds quick and listener fired with the dialog immediately added). What seems to be happening is the nav operation, i.e. pushAndPopUntil, has not yet completed updating its internal _history stack, while the dialog is being added, so somewhere along the way it's inadvertently popping the dialog.  

Which explains in my case why a delay before launching the dialog helps, or navigating to my page with a simple push (that contains no pop operation) also works.

But I do not know if this is related to any minor timing overhead added with auto_route or if it's a deeper flutter Navigator issue?

What I can see though is that immediately before the dialog is launched, the auto_route stack looks accurate, but the Navigator _history is not accurate since I can see pages in the list that have yet to be removed.

**Comment by ShelMax** [comment]
Same error, but in my case, I use `AutoRouter.of(context).replace()` and i cant close dialog in the new page, if change to `AutoRouter.of(context).push()` all work fine, and I can close dialog. Also, I revert the plugin version to 2.4.2, and it all was fixed.

**Comment by ShelMax** [comment]
Checked with `.pushAndPopUntil();` and get the same result, I can't close the dialog on the new page.

**Comment by itaishalom** [comment]
But push requires a route parameter, isn't it?

**Comment by shohibexlab** [comment]
I also had the same issue.
I was passing popup Context wrong.
The solution in my case was that I passed the current page's **context** to **showDialog**(any kind of dialog or modalSheet).

_Showing popup reference code:_
`await showSimpleDialog(
  context: context,
  body: Container());
 // context is coming from the current page, from where the popup is being called
`
_Exiting popup:_
`
onPressed: () async {
  context.popRoute(); 
}, // Must use the same context that we passed!`

I hope it helps someone! Thank you!

**Comment by Ali-Almezead** [comment]
i still have same problem any solution ?

**Comment by Mayb3Nots** [comment]
In my case I was using nested navigation and because of `useRootNavigator` when calling `context.popRoute()` the dialog doesn't exist in that context which means it will pop the page. To fix this you have to pass `useRootNavigator` to `false`

**Comment by Mayb3Nots** [comment]
> @Ali-Almezead @Mayb3Nots router.popTop() should help

I tried but it didn't work. My solution is still the only way for it to work.

**Comment by msgtobala** [comment]
Pass proper context to the  `Navigator.of(context).pop();`

This is what I have done,
`
void onClose(BuildContext context) async {
    Navigator.of(context).pop();
}

IconButton(
  icon: const SVGLoader(image: icons.Icons.copyBlack),
  onPressed: () => onCopy(appointmentId),
  color: ThemeColors.black,
),
`

**Comment by NijatTagizada** [comment]
> In my case I was using nested navigation and because of `useRootNavigator` when calling `context.popRoute()` the dialog doesn't exist in that context which means it will pop the page. To fix this you have to pass `useRootNavigator` to `false`

it worked for me. thanks a lot
