### ISSUE TITLE
Navigator.pushAndRemoveUntil for web?

### ISSUE THREAD

**Issue by angwandi** [Milad-Akarie/auto_route_library#784]
What is the actual value of Navigator.pushAndRemoveUntil for web?

I have tried : 
```
context.navigateTo(const WelcomeRouter());
context.navigate(const WelcomeRouter());
context.replace(const WelcomeRouter());
```
All not clearing the history on the web but working fine on mobile.

**Comment by Rammehar** [comment]
Thank you very much I am new to Auto Route library. pls also share the code for "UnAuthWrapperPage"

**Comment by Rammehar** [comment]
Wow every nice great work man, thanks a lot. I am new to auto route library doesn't know much. Thanks you very much again.

**Comment by Hennythehun** [comment]
@Rammehar I updated the comment above. It's just the reverse of the AuthWrapperPage. Your error is not specific enough to decipher. However, understanding what the code does might help you fix it:

- AuthWrapperPage is a wrapper that will be triggered each time a user wants to navigate to its child. It checks that the user is authenticated. If they are authenticated, it builds the page normally by returning an AutoRouter() widget. Otherwise it directs the user somewhere else, in this case - UnAuthRouter (ie UnAuthWrapperPage).
- UnAuthWrapperPage does the opposite of the AuthWrapperPage. If the user tries to navigate to say login/signup page it will redirect to the Authenticated route instead. Fortunately, AutoRoute is smart enough to the route stack, so therefore the user appears to stay on the same page.
