### ISSUE TITLE
AutoTabsScaffold's routes with arugments 

### ISSUE THREAD

**Issue by Arnooodles** [Milad-Akarie/auto_route_library#786]
Hi, 

I have an AutoTabsScaffold with routes that have required arguments. 
```
AutoTabsScaffold(
...
routes: [ 
Tab1Router(data: data),
Tab2Router(data: data),
Tab3Router(data: data),
Tab4Router(data: data),
]
...)
```
But when I run the app it had an error "Tab1RouterArgs can not be null because it has a required parameter"

How do I fix this? Or Is there another way to pass my data to the tabs

**Comment by wer-mathurin** [comment]
@Arnooodles and @Milad-Akarie 
I was able to do it without InheritedWidget.  But I encounter the same error, because one of my tab was have nested routes, so the tricks si to pass children to it like this:

```
......
 routes: [
          const TenantBuilderRoute(),
          ProfileRootRoute(account: account.me, 
             children: [
                  ProfileRoute(accountEntity: account.me)
             ])
        ],
      ),
.....
```

@Milad-Akarie : I think this can be better documented there: https://autoroute.vercel.app/basics/nested_routes
