### ISSUE TITLE
Navigate to same route but have multiple route transitions

### ISSUE THREAD

**Issue by nmarko91** [Milad-Akarie/auto_route_library#819]
Let's say i have:

```
CustomRoute(
      transitionsBuilder: TestTransitions.slideRightToLeft,
      page: TestScreen,
      path: '/test',
);
```

And I have 2 buttons on home screen:
- on tap of button 1 should navigate from home screen to the `TestScreen` sliding from right to left
- on tap of button 2 should navigate from home screen to the `TestScreen` sliding from left to right

button 1 tap is `AutoRouter.of(context).push(TestScreen());`and it will slide the route from right to left.

But how can I navigate to the same route with left to right if I click on button 2

**Comment by Milad-Akarie** [comment]
@nmarko91 have you tried customRouteBuilder?

**Comment by nmarko91** [comment]
Haven't seen that one - I'll take a look at that, thanks 🙏

**Comment by jseminck** [comment]
Hello, I wanted to post the same question and found this thread. 

Our current approach to do this is to use `customRouteBuilder` and there in the `transitionsBuilder` we can decide which transition to use depending on where we come from. (e.g. if coming from route A, use slide right to left transition -- if coming from route B, use slide left to right transition).

Another option I see is to add some unverisal prop to each screen which that has custom transitions named "transition" and check that in the `customRouteBuilder` and apply the transition based on that. This feels a bit hacky but on the other hand I like it because the prop gives the developer that is working on the screen an indication that this screen does have custom transitions (and therefore doesn't break it).

Do you have any advice or other ideas? That's very much appreciated. And also a big thanks for the library, it works amazing!
