### ISSUE TITLE
Documentation about nested navigation via clicks inside  a AutoTabsScaffold ?

### ISSUE THREAD

**Issue by RageshAntony** [Milad-Akarie/auto_route_library#941]
In an AutoTabsScaffold , how to do nested navigation and pass arguments  ?

For example,

```
AutoTabsScaffold(
        routes:  [
          A(args),
          B(args),
          C(args),
          D(args)
        ],
```

Now in any one of the 4 rtab outes , how to navigate to it's children with arguments passing ?

Such as ,

A <=> A1 (arg) <=> A2 (arg) <=> A3(arg)
B <=> B1 (arg) <=> B2 (arg) <=> B3(arg)

There is no docs about complex manual nested navigation . only about some NavLink widgets that looks like another tabs !!! .. 

2)
How to pass args  to EmptyRouterPage's  initial children ?

```
 AutoRoute(
            page: EmptyRouterPage,
            children: [
          AutoRoute(page: NotificationsView,initial: true,), // need to pass a Class object here ex:  NotificationsView({ this.cable});
          AutoRoute(page: InfoView),
          AutoRoute(page: NavView),

        ]),
```

Callng it in an AutoTabsScaffold 
```

        routes:  [
          HomeMainViewRoute(cable: cable),
          ListsViewRoute(cable: cable),
          EmptyRouterPageRoute(), , // need to pass a Class object here to its initial child
          SettingsViewRoute(cable: cable)
        ],
```

**Comment by RageshAntony** [comment]
@Milad-Akarie please help me ... Sorry it's urgent . In a confusion

**Comment by Milad-Akarie** [comment]
@RageshAntony  replace empty router page with your own regular flutter widget with whatever constructor arguments and have it  return an AutoRouter() widget eventually

**Comment by RageshAntony** [comment]
> @RageshAntony replace empty router page with your own regular flutter widget with whatever constructor arguments and have it return an AutoRouter() widget eventually

Please provide an example?

**Comment by percula** [comment]
I would also appreciate a more complex and working example. I have bottom navigation, with my app structure something like:

BottomNavigationBar:
  -AList
    -ADetail
      -AMoreDetails
  -BList
    -BDetail
  -C
  -D
  
The problem I ran into was routing from "BDetail" to "ADetail". It added "AList" into the stack, so instead of going back to "BDetail" on back press, it went to "AList". I tried fixing this by making a copy of "ADetail" and its children under "BDetail", but I kept running into errors saying that the parent route wasn't added.
  
Anyway, if you can add a complex example like this, it would be very appreciated. The o examples provided are very basic and not much help past the initial setup of the bottom navigation bar and main pages. I ended up changing over to Beamer, but if AutoRoute can actually do this, I'd certainly resurrect that branch since it's much simpler.

**Comment by RageshAntony** [comment]
@Milad-Akarie How to refresh each bottomnav tabs when switching them to it ? That is is there any listeners exists  ?
