### ISSUE TITLE
Preventing Pop on Page

### ISSUE THREAD

**Issue by SergeiKanerva** [Milad-Akarie/auto_route_library#976]
[ Not at issue ] 

Hi, thank you for this project, works great. 
Have one question:

I have: Starting Page, Login Page and Main Page.
On first load user gets to Starting Page -> Login Page, gets token, goes to Main Page
On next load ( if token exists ) -> user redirected from Starting Page to MainPage instantly. 

How I can disable .pop and android back-button on MainPage to prevent user going to Starting Page?
For redirecting using context.router.push(MainPageRoute()). Thanks!

**Comment by Milad-Akarie** [comment]
@SergeiKanerva  it seems like you shouldn't keep `StartingPage` in your stack in the first place. 
when you navigate to `MainPageRoute` use replace instead of push 
`context.router.replace(route):`
also consider using `AutoRouteGuards` for conditional redirecting. 
https://pub.dev/packages/auto_route#route-guards

**Comment by SergeiKanerva** [comment]
That was helpful, thank you!
Closing the issue
